### ISSUE TITLE
Some modules not loading

### ISSUE THREAD

**Issue by msintros** [bogaudio/BogaudioModules#10]
Switch, Reftone, DGate and a few other utilities are not showing up in VCV Rack.  Running OSX 10.9.5

**Comment by mdemanett** [comment]
That's weird.  Two questions:
1. Do any of the Bogaudio modules work?  Like Shaper?
2. For Reftone, etc, are they listed in the add-module window, but don't load, or just not listed at all?

In any case, the thing to try is manually update to the [latest version](https://github.com/bogaudio/BogaudioModules/releases/tag/0.5.4): in your Documents/Rack/plugins directory, delete any and all previous versions (if there are somehow multiple copies of Bogaudio, it might cause this), and then unpack the new and restart Rack if it's running.

(Note that Rack's module updater is currently disabled, thus has to be a manual update.)

Hope that helps!

**Comment by msintros** [comment]
Thanks, that did help.  I had tried manually adding the missing modules but that didn't work.  I did indeed have to get rid of everything and add all of the new versions in, even the ones that were working.  The missing ones weren't even showing up in the add-module list, but everything appears to be working now!

**Comment by mdemanett** [comment]
Great, good to hear!
