### ISSUE TITLE
Module request: building on ADDR-seq idea

### ISSUE THREAD

**Issue by bubbleandsquawk** [bogaudio/BogaudioModules#100]
Hi Matt. Thanks again for your excellent collection of modules.
I was wondering if you would be interested in doing a module that operates similarly to the ADDR-seq but rather than being cv addressed it is gate addressed. Eg. it takes up to 8 inputs and selects sequence stages by gates on their corresponding inputs. It would allow for similar functionality as something like Make Noise Pressure Points.

**Comment by mdemanett** [comment]
I think have something like that on a todo list somewhere...it'll happen, but can't say when.

**Comment by mdemanett** [comment]
See PGMR and PGMRX in the new release.
