### ISSUE TITLE
New VCF bug

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#101]
Hi and thanks for your updates! I've got a HUGE loudest and overdrive output on settings like this while turning FREQ  knob. So in short we've got such uncontrollable overdrive output when slope above 8 and freq about below 100hz on any filter mode. Hope that info will help.
![2020-02-14_21-21-58](https://user-images.githubusercontent.com/42435368/74557018-52110500-4f70-11ea-8cff-a796344116a1.png)

**Comment by mdemanett** [comment]
Thanks for catching that -- definitely a problem.  I pushed up a quick fix just now, if you want to try it, though there is more work to do -- it's better, but a quick sweep from a high cutoff down to zero still spikes the gain.
