### ISSUE TITLE
Gate out from ARP not working as it should

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#102]
As the title says. Sometimes it takes a while before the gate picks up.
Here is a test patch.
![Bog Arp Gate](https://user-images.githubusercontent.com/46076474/75365845-16eeca00-58be-11ea-9150-eb59f009a04f.png)
The bottom FM is triggered by the clock out and the top one by the gate out from ARP.

[BOG ARP test - 26022020.zip](https://github.com/bogaudio/BogaudioModules/files/4256955/BOG.ARP.test.-.26022020.zip)

Greetings Peter.

**Comment by mdemanett** [comment]
Bug confirmed -- lI'll see what I can do about it.  Thanks!

**Comment by Petervos2018** [comment]
Not fixed in 1.1.27 maybe next update ;)
Greets Peter.

**Comment by mdemanett** [comment]
Do you have another example?  That patch works for me...

**Comment by Petervos2018** [comment]
Are you sure ? I think you are , but that patch still gives me the same "error".
It takes a while before the gate from the upper ARP is picking up.
Windows 10.
Greets Peter.

**Comment by Petervos2018** [comment]
OK , here is a new example , this time I use a keyboard.
Play a four note chord start the clock and......
[BOG ARP Keyboard 21032020.zip](https://github.com/bogaudio/BogaudioModules/files/4362208/BOG.ARP.Keyboard.21032020.zip)

Greetings Peter.

**Comment by mdemanett** [comment]
I think I fixed it this time -- the part I was missing when I was trying it was to stop and start the clock again.  I think the first time I tried your patch, I turned the clock on, and then when I came back later the clock was already on so I didn't see the problem.  Thanks for bearing with me and for the extra examples!

Anyway, there's still a bit of an odd behavior when starting the clock, in that the first gate will be longer than it probably should be.  This is a consequence of having the gate length be a percentage of the clock interval.  I added a new context-menu option to have the gate length ignore the clock entirely.

**Comment by mdemanett** [comment]
Requested a build with this fix, so it should be available in a few days.

**Comment by Petervos2018** [comment]
> This is a consequence of having the gate length be a percentage of the clock interval. I added a new context-menu option to have the gate length ignore the clock entirely.

Yep first step is a bit different, but I think this is as much solved as it will ever get.
Thanks Matt, for this, and all you other modules,

Greetings Peter.
