### ISSUE TITLE
FM-OP with CV-Map

### ISSUE THREAD

**Issue by midiguru** [bogaudio/BogaudioModules#103]
I don't know if this is an issue with FM-Op or something else. It's hard for me to diagnose, but maybe you'll have an idea about it. The issue is this: I like using stoermelder CV-Map to control the attack and release times in the internal ADSR of FM-OP. But this will sometimes cause the VCV audio engine to blow up. My mixer and output devices show bright yellow on their jacks, and Nysthi multivoltimetro reports "nan" as the signal.

I suspect that the problem has to do with using a sawtooth wave as the input to a CV-Map channel. When I switch to sine waves as my LFO inputs, the software behaves nicely.

This seems not to happen with modules other than FM-OP. Here's a simple patch that shows it. Turn on the clock and then add a mod routing through CV-Map from channel 1 to the FM-OP's attack time. It may work fine for a few repetitions, but shortly it will cause the audio engine to malfunction.

[engine_blowup.zip](https://github.com/bogaudio/BogaudioModules/files/4303803/engine_blowup.zip)

**Comment by mdemanett** [comment]
Fixed it, I think.  Should see a release soonish.  Thanks for the heads up and detailed explanation/patch.
