### ISSUE TITLE
is a new VCF CV input slewed? 

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#105]
Noticed that when putting typical AD repeated envelope with 0ms attack while in LP mode (or HP), so pretty spiky one. But got pretty slewed result then with any position of cutoff knob. Tested that envelope with most linear vult stabile filter and got pretty spiky result as expected. Is that feature or? Just curious.

**Comment by mdemanett** [comment]
It does have slew -- it's there as a workaround...too fast movements in the cutoff can cause the filter to misbehave.  

For the record, there's also a fixed 2-pole highpass at 80hz cutoff on the output for similar reasons.
