### ISSUE TITLE
POLYCON 8 channel suggestion and external CV inputs as well

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#106]
Thank you for Polycon module, it's a real compact thing to make a complex control of any poly module.
What do you think on making 8 channel version? Also I'd like to see external CV inputs near the each knob to apply some modulations when needed. In that way we can get a handy merger tool with offsets and external CV controls without messing so much with additional split\merge modules. 
Thanks for your work again! Bogaudio makes life easier very often!) 
EDIT - I'd also like to suggest add RANGE option in right click menu like you did in ADDR sequencer.

**Comment by mdemanett** [comment]
Hey, glad to hear it's useful.  I think something like what you're saying would be cool, will look into it.
