### ISSUE TITLE
PGMR poly clock mode suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#107]
Hi and thanks for the new awesome PGMR! I have one suggestion on it - now if we put a poly clock into it we will get same row sequences but with different steps according to the each clock. Could you add an option for distributing each of 4 polyphonic clock signal to each ABCD output? In that way we can get four fourstep sequences with different clocks. IMO it would be pretty useful for some reasons. 
EDIT: also noticed a bit higher cpu consumption for sequencer on my system - 3.5% even in mono mode.

**Comment by mdemanett** [comment]
Hey, I think I get what you mean...also think I'm not going to do it, because it's kinda complicated, and I'm not sure how that mode would interact with the expander PGMRX.  

I'm working on the CPU usage, though.
