### ISSUE TITLE
Matrixmixers: Option to skip the inverse connection

### ISSUE THREAD

**Issue by Deevje** [bogaudio/BogaudioModules#108]
Hey Matt,

I was very excited when you announced your Matrix Mixer Modules, hoping they would bring the exact functionality I was waiting for in such a module. I especially had my hopes up for the 16x16, since this would make my recreation of the VCS3 Synthi a lot more compact.

I'm really happy with the lights and colors indicating status, this is already a big improvement in practicality!

Only problem is, and the reason I can't get used to using them, is the fact that I have  to go through an inverse connection in order to "pull out a pin from the patch matrix".

My idea for a solution would be to disable the right mouse button parameter box, like on your mixers' solo/mute buttons, in favor of using it to make an inverse connection, this way I feel it would be more intuitive to use these actually awesome mixers!

If this would prove to be more difficult than I can estimate,  might it be possible to have an option in the menu to either specify behaviour or possibly uncheck the whole inverse connection option?

Hope to hear what you think of this idea!
Keep up the awesome work!

Kind regards
Deev

**Comment by mdemanett** [comment]
I like having the invert and right-click to set an arbitrary attenuation -- the Synthi had special inverting and attenuating pins, after all.

That said, I was playing with it and it can be kinda wonky.  I added an option like you suggest to have left clicks on the button only toggle on (positive) and off.  Right-click can still set a negative.

Also fixed a bug where right-clicking would toggle the switch.

Cheers.

**Comment by Deevje** [comment]
That's awesome! Thank you! I;m looking forward to trying it out!

Cheers!
