### ISSUE TITLE
Switch module: Option to keep the saved state?

### ISSUE THREAD

**Issue by Deevje** [bogaudio/BogaudioModules#109]
Hey Matt,

I noticed that the Switch module doesn't keep the position it was in as I saved the patch, would it be possible to make this an option in the menu?
The current behaviour makes sense when used for low/high functionality, but I tend to use it as an A/B switch. Your module seems to be the only one capable of conveniently switching like this, and I love how small it is.

Hope to hear what you think of this idea!

Kind regards,
Deev

**Comment by mdemanett** [comment]
I like it, will do for the next release.

**Comment by Deevje** [comment]
Awesome, thank you so much for listening to these suggestions!

All the best!
