### ISSUE TITLE
Stack usage?

### ISSUE THREAD

**Issue by bitfetcher** [bogaudio/BogaudioModules#11]
Thanks for this amazing collection of modules! They're quite useful, use minimal rack space, and I especially love the clean "look-and-feel" of them all!

I must not understand the Stack module because I can't get it to do much. I presumed an oscillator input on the V/OCT input would be copied to the THRU, and re-pitched on the OUT, per the settings of the OCT and SEMI controls. What I hear is a nearly imperceptible difference between the two outputs, regardless of the OCT and SEMI control positions, QZ button, and CV input positions/connections. A little snooping with a Scope seems to showsthe input gets rectified a bit...

Thanks again for these modules, and any help you can give lifting the fog from my eyes (ears?)!

**Comment by mdemanett** [comment]
Hi -- glad you like the modules!

Sounds like you're routing the oscillator output (audio) through Stack?  It's instead meant to process the 1volt/octave pitch input to the oscillator.  Which is to say it goes before the oscillators in the signal chain -- e.g. patch the v/oct port of "Midi to CV" to the input of Stack, then patch Stack's outputs to the v/oct inputs of two oscillators.

**Comment by bitfetcher** [comment]
Ah, the only configuration I didn't seem to try! Works like a charm, and thanks again!!

**Comment by mdemanett** [comment]
Great, good to hear!
