### ISSUE TITLE
Unity mixing for matrix Switches

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#110]
Hi Matt! Your SWITCHes modules are awesome! But can you add unity mixing to them? I found that your MIX module which can mix AB signal works as unity mixer and I really love it, there will be no clipping or so. Or maybe I don't understand how unity actually works..
EDIT: I meant this all for mixing audiorate signals and when no invert option is selected, only 0-100% +

**Comment by mdemanett** [comment]
Hey...I think what you want is to set "Output clipping" to "Hard" on the context menu -- it will clip at +/-12V but with precise summing and no distortion.  The default "Soft" does a soft limiting / saturation thing.

If you're looking to avoid hitting the limit at all, the the "Input gain" option let's you cut the inputs by as much as -12db.
