### ISSUE TITLE
Switch1616 when midimapped "click to invert" option doesn't make sense

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#111]
It seems that when buttons are midi mapped (I mapped this with toggle or latch ones from midi controller)  they ignore your new and awesome click to invert option (disable state). So when low state of toggle is zero it will be ignoring, but when = 1 from midi it works ok.
EDIT: sorry, it shows nearly zero only around 63 or 64 CC message from midi controller, tooltips says 0.7343 percents

**Comment by mdemanett** [comment]
I added another option to disable inverting entirely, so a midi CC with with value 0 will turn the switch off instead of setting it to invert.

**Comment by vcvrackideas** [comment]
Thanks Matt! A game changer!
