### ISSUE TITLE
bug switch1616

### ISSUE THREAD

**Issue by matthleg** [bogaudio/BogaudioModules#114]
Hello for me in win10 the new switch1616 doesn't work : 
1-switches doesn't change nothing
2- If I plug cables in 1a or 2b or 3c or 4d... I have just noise (and the switch doesn't change  nothing)
3- if I plug cables in 1b or 1c or 1d... I have just silence
Thanks for the work and I hope it is just a small bug.
Have a nice week end.
Matthieu

**Comment by mdemanett** [comment]
This is what happens when I "optimize" things late at night.

Will request an updated release soon.

**Comment by mdemanett** [comment]
This is fixed(in the new release now available.
