### ISSUE TITLE
VCF resonance issue

### ISSUE THREAD

**Issue by MarcBoule** [bogaudio/BogaudioModules#115]
Hi Matt, this was discussed in facebook, but I'm leaving a trace here also for you in case it's useful. If we patch VCO into VCF, all in their default modes, then turn the cutoff freq down to 0 in VCF, the output is 0V as it should be; but then if we turn resonance all the way up, and then back down again, the output doesn't come back down to 0 but instead stays stuck on NAN.

![image](https://user-images.githubusercontent.com/33604154/80394634-1c49a000-8880-11ea-94bb-28da3043343f.png)

**Comment by mdemanett** [comment]
Thanks Marc!

**Comment by mdemanett** [comment]
New release today has this fix.
