### ISSUE TITLE
AD's RT toggle does not seem to work

### ISSUE THREAD

**Issue by wapiflapi** [bogaudio/BogaudioModules#117]
Hey! Thank you for all the awesome modules, they're a joy to use.

I don't know if'm doing something wrong, but I don't seem to get AD's retrig toggle to work.

![Screenshot from 2020-05-12 22-43-30](https://user-images.githubusercontent.com/1619783/81743502-08b65000-94a2-11ea-8063-0d8a125c041d.png)

I expect the enveloppe to re-trigger on each clock signal when the toggle is lit, but I don't see any difference between the two states of RT toggle. (on the screenshot the AD on the left should be re-triggering but it isn't.)

Let me know if I can be helpful by providing more info on this issue!

**Comment by mdemanett** [comment]
Bug confirmed, and fixed...not sure when this will get to the Rack plugin manager, but you can get a test build with the fix [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.31-test1) if you want.  Thanks for the detailed report!

**Comment by wapiflapi** [comment]
That was quick! Thank you for taking a look at it :-)

Looking forward to going back to two ADs instead of having Rampage in my patch :p
