### ISSUE TITLE
Slew I cant get it doing its thing

### ISSUE THREAD

**Issue by XtremeSounds** [bogaudio/BogaudioModules#119]
Hi Im trying to make a rising bassline. For some reason its hit or miss. what is not set corr
![Capture](https://user-images.githubusercontent.com/49108783/83757734-efd33180-a63e-11ea-9756-7685b57c172d.JPG)
ectly?

**Comment by mdemanett** [comment]
Really not sure.  Maybe send the voltage out of slew to the scope, see what it's doing.
