### ISSUE TITLE
build fail with GCC 5.3.1 (and solved)

### ISSUE THREAD

**Issue by davephillips** [bogaudio/BogaudioModules#12]
Fedora 23 Linux

g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Isrc -Isrc/dsp -Wsuggest-override -std=c++11 -c -o build/src/dsp/oscillator.cpp.o src/dsp/oscillator.cpp
In file included from src/dsp/oscillator.cpp:3:0:
src/dsp/oscillator.hpp:199:79: error: ‘NULL’ was not declared in this scope
  void setPartial(int i, float frequencyRatio, float amplitude, float* phase = NULL);
                                                                               ^
../../compile.mk:53: recipe for target 'build/src/dsp/oscillator.cpp.o' failed

Solved by adding #include <cstddef> to src/dsp/oscillator.hpp

**Comment by davephillips** [comment]
Ach, I freaking hate editors that don't show the angle brackets. If you didn't already figure it out, the needed include is cstddef. Sorry about that.

**Comment by mdemanett** [comment]
I used stdlib.h instead but it should also do the trick -- does it work for you?  

Oddly on my linux install (ubuntu 17, gcc 7) it built without the change.  (And on OSX, where I usually work.)  I haven't figured out why some headers seem to be implicitly included on some systems/compilers but not others.
