### ISSUE TITLE
Walk and Walk2 Issues at higher sample rates.

### ISSUE THREAD

**Issue by Alexanders101** [bogaudio/BogaudioModules#120]
## Steps to reproduce
1. Start with a blank rack. Add a Walk or Walk2 module (in my case Walk2).
2. Set sample rate above 48 khz (in my case 96 khz)
3. Module will not move until the rate is adjusted to above exactly **20.875**, at which point the random walk will start.

It also seems that even when the random walk is working, it moves faster than the same rate at a 48 khz sample rate.

**Comment by mdemanett** [comment]
Good catch, thanks for the report.  I fixed both problems, though I can't say when the fixes will get released to the plugin manager -- if you want it, a build with the fix will be available for manual install [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.31-test2).

**Comment by Alexanders101** [comment]
Looking good! Thanks for the quick fix.
