### ISSUE TITLE
Mix 4, channel led not resetting when disconnected

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#121]
Hi Matt,

when pulling out a signal cable from any channel above channel 1, the signal led stays at the last received signal.
I see this on Mix 4, might be as well on Mix 8, i have not checked.
![mix4-bug](https://user-images.githubusercontent.com/40998416/84262063-37fdc280-ab1d-11ea-9e41-63597dc7e73b.png)

**Comment by mdemanett** [comment]
Hey Latif, fixed it -- thanks good catch.
