### ISSUE TITLE
Anti-pop filters for Switch matrix

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#122]
Hi Matt! I found switch44 very useful for routing and use it with saved presets via stoermelder 8face, pretty happy with that! However I found that enabling\disabling buttons generates audible clicks in audio domain and in the case when switching overall preset for this module (switch44) it becomes 4x clicks all together. I think there are already modules in VCV that have this feature, afaik mindmeld mixers for solo and mute buttons. In the case if this filter would consume a CPU a bit more it could be a right-click option which would be cool in use for audio and maybe useless for CV (but who knows maybe useful to get a bit of slew?)
Cheers!

**Comment by mdemanett** [comment]
Hey, yeah, good idea, will do.

**Comment by vcvrackideas** [comment]
> Hey, yeah, good idea, will do.

Thanks for the work, it's working cool now! Switched 3 effects together with 8face and here only some nicely a bit of noise that very reminds me how switches works in analog. Thanks again Matt!
