### ISSUE TITLE
Issues with PEQ6 & PEQ14

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#128]
Hi Matt,

part of post : 

> I can’t seem to get any audio from the individual channel outs unless there is a cable also patched to one of the main, odd, or even outs.

>The second issue is I can’t get BW to respond to CV no matter what I do. The knob still functions but there’s no change from CV. Any clues as to what I might be missing?

Kudos to Matt for these great modules! They’re exactly what I’ve been needing.

As seen here : 

https://community.vcvrack.com/t/issues-with-peq6-peq14/10599

Greetings Peter.

**Comment by mdemanett** [comment]
Thanks Peter, will get those fixed.

**Comment by Petervos2018** [comment]
Thanks Matt, I think this is fixed now.

Closing 👍
