### ISSUE TITLE
Feature suggestion for DGate module!

### ISSUE THREAD

**Issue by jaffasplaffa** [bogaudio/BogaudioModules#129]
Hey :) 

I would like to suggest input for modulating gate time on the DGate module. You can for example use a sequencer with a row of knobs and then use the knobs for each step to set a specific gate time for each step. I think it will make sequences more interesting and "alive".

Best wishes,
Jakob

**Comment by mdemanett** [comment]
Interesting idea...I'd have to redesign it as a larger module to fit the ports, but will think about it.

Note you can do this now with DADSRH+, which has a CV-control over each stage including delay.  For an alternative in less HP, you can use the AD module as a CV-controlled timer for the delay, then use its EOC (end of cycle) output to trigger another AD to produce the gate, with attack zeroed out and applying CV to the decay time.

**Comment by jaffasplaffa** [comment]
Thanks for the fast response :) 

I am kind of already working on a similar module, where I think I might add that feature.

But just thought I'd suggest it anyway :)

**Comment by VegaDeftwing** [comment]
You might be able to add a switch on each of the PGMR's outputs to output as a gate length realative to the clock rate rather than the CV of the knob position. This would obviously be awkward as a step is selected manually, but even that sounds like a good feature albeit I'm not sure the best way to handle it musically.

**Comment by mdemanett** [comment]
@VegaDeftwing if I understand, you can achieve that by using a CV out from PGMR to control the decay length of an AD, where AD is triggered by the clock, and it's out is used as the gate?

**Comment by VegaDeftwing** [comment]
Sort of. That makes it so the delay length is set directly by the knob position instead of as a division of clock timing, making it so that adjusting the clock rate changes the realative gate width. This can easily result in turning the clock fast enough that a previously square wave turns into a DC offset.

I hope that makes sense?

**Comment by mdemanett** [comment]
Oh, yep, that makes sense.  Maybe there should be a module for that (and probably there is already, in some other collection) -- that takes a clock, has a gate length knob and CV, and outputs a clock-relative gate.  ARP actually does this, but without a gate length CV.

**Comment by VegaDeftwing** [comment]
At least as far as I could tell there's nothing that serves the purpose
well, at least no clean, single module solution.

**Comment by VegaDeftwing** [comment]
<img width="1262" alt="lengthseq" src="https://user-images.githubusercontent.com/11283620/89852859-6ca9ec80-db55-11ea-8911-ae6de18165fb.png">
This was about as close as I could get.

**Comment by mdemanett** [comment]
Cool, I'll look into making something.

**Comment by VegaDeftwing** [comment]
Sweet. Also, I realize it's a separate issue, but if this is potentially going to require a redesign of PGMR's panel to some extent anyway: It'd be nice to have CV control over the forward/reverse switch and/or phase based clocking to provide the same functionality- I can open a separate issue for that if you like

**Comment by mdemanett** [comment]
You can use a negative clock pulse -- see the documentation for [8:1](https://github.com/bogaudio/BogaudioModules#eightone), the bit about option "Reverse step on negative clock".  Turn that on and process the clock with INV, which is a CV-controlled inverter.

**Comment by mdemanett** [comment]
So I went ahead and made a clock relative gate utility, RGATE.  It also divide/multiply a clock.  In the new build [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.33-test6).

An inherent difficulty with this sort of thing is that you really need to have seen two clock pulses to know the clock period, to set the output gate length.  So it outputs a fixed gate on the first clock received, which is modestly customizable on the context menu.

Then, if you use a steady clock, all should be peachy.  An irregular clock will have odd effects.  Starting and stopping the clock complicates things...to deal with that, I put in a RUN port and way too many context menu options about what it does.  

Real documentation will be forthcoming when this releases for real; for now here's a sample patch.  The first four steps from PGMR vary the gate length, and the last four use the multiplier to do ratchets.  Also it starts and stops with the clock.
![Screen Shot 2020-08-12 at 1 32 08 AM](https://user-images.githubusercontent.com/49971/89978543-c1c02e00-dc3b-11ea-9edc-df16addb0b7a.png)


[rgate.vcv.zip](https://github.com/bogaudio/BogaudioModules/files/5060778/rgate.vcv.zip)

**Comment by VegaDeftwing** [comment]
It's nearly 1am here, so I can't test it now; however, this looks absolutely amazing! I'm really looking forward to trying it out tomorrow!

**Comment by VegaDeftwing** [comment]
Got a chance to test it out, first just checked for bugs- seems to work impressively well, actually working as a pretty interesting sub-octave generator with pwm capabilities when fed a square wave osc. Otherwise, for it's normal use case it worked pretty much exactly as expected and was a heck of a lot of fun.
![image](https://user-images.githubusercontent.com/11283620/90050902-7b4eeb80-dc9c-11ea-83e4-174d69bdd76c.png)

**Comment by mdemanett** [comment]
Nice, that's for giving it a whirl!

**Comment by mdemanett** [comment]
RGATE is in the new release available on the library.
