### ISSUE TITLE
Feature suggestion for the PEQ6 and PEQ14

### ISSUE THREAD

**Issue by omricohenmusic** [bogaudio/BogaudioModules#130]
Hi Matt,
I really enjoy the new PEQ modules, and I find them really useful for parallel processing via the individual band outputs. The thing is, it would be great to have the option to take out connected outputs from the main output. What I mean is, let's say that I send band for to a reverb and from there to the mixer, and it will not come out also from the main output, only the rest of the bands, the ones that are not connected, will be mixed. It will make parallel processing much easier. Does this make sense? 
Thanks so much!

**Comment by mdemanett** [comment]
Hey Omri, yes makes sense and sounds useful.  Will look into it!

**Comment by omricohenmusic** [comment]
Thank you so much!

Omri Cohen

[https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abnExMEkyNGRPbWc&revid=0B8K00I2KYl3aT0xhRkhBcFU3Zk5YeWZrRFMrNitpRElSUWo0PQ]<http://omrico1983.wixsite.com/omricohencomposer>  <https://soundcloud.com/omricohencomposer/tracks> [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aMXU1emw5eVZIODA&revid=0B8K00I2KYl3aRHRtN0l5R2w2bG42UzQzMmF6WEVpL3JNMnpzPQ] <https://www.facebook.com/omricohenmusic/>   [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aY0ZmdDJVRTkyWVE&revid=0B8K00I2KYl3ab2s2Qm5XNDg5c1d0RlVyTE5XWUVwOXBHbERzPQ] <https://soundcloud.com/omricohencomposer/tracks>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aM2VYYkdMOTBibEE&revid=0B8K00I2KYl3aY2pJcTcycHhDc2ZkeEpsUHlVd25sS0RmQVpnPQ] <https://www.instagram.com/omricohencomposer/?hl=en>  [https://www.linkedin.com/in/omri-cohen-b01b70150/] <https://www.linkedin.com/in/omri-cohen-b01b70150/>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abkliN1pfQk5lSG8&revid=0B8K00I2KYl3aZ2Q5R0lINlVYZ0RDeWI4Um53Z3NSdG1La3NvPQ] <https://omricohencomposer.bandcamp.com/>


<https://www.facebook.com/omricohenmusic/>
<https://www.facebook.com/omricohenmusic/>

________________________________

**Comment by mdemanett** [comment]
This change is available on the library.

**Comment by omricohenmusic** [comment]
Thank you so much!On Aug 17, 2020 04:12, Matt Demanett <notifications@github.com> wrote:
This change is available on the library.
