### ISSUE TITLE
PEQ: Bandpass, or peak-style EQ filters?

### ISSUE THREAD

**Issue by jamshark70** [bogaudio/BogaudioModules#131]
I was looking for a standard parametric EQ (zero gain at the edges of the spectrum, boost/cut in the middle) but it seems PEQ's bands "appl[y] a bandpass filter" (quoting the manual)... and indeed I hear severe attenuation of high frequencies, which a proper EQ unit will not do unless asked to apply a high shelf or LPF. (I did disable the LP and HP switches btw.)

Is this a misnomer? The name "PEQ" = parametric EQ certainly fooled me.

Would love to have a switch for EQ-style filters rather than BPF.

**Comment by mdemanett** [comment]
I think you just want to turn the LP and HP switches back on.  With them on, they're your shelving filters, happy day.  With them off, then it's a bank of independent BP filters, which is a different use, and yes not an EQ anymore.

**Comment by jamshark70** [comment]
> I think you just want to turn the LP and HP switches back on. With them on, they're your shelving filters, happy day.

Ok, I was reading the documentation where it says "The first channel may be configured as a lowpass filter, if the LP button is on. The last channel can be highpass" -- which sounds like, switch on = lowpass, switch off = the shelf that you mentioned.

So, when the first and last bands are shelves, then the middle band must be a boost/cut EQ filter? Because it's not useful for a shelf to operate on frequencies that a bandpass filter is removing (assuming that the filters are in series, as they typically are in an EQ unit).

(It's moot at this point, since I found Vult Incline, which is unambiguously an EQ. So if you'd prefer to close this, that's fine -- just pointing out some confusion from the user's perspective. Btw some other Bogaudio modules, I like a lot -- the FM operator is a great design.)

**Comment by mdemanett** [comment]
It may be helpful to know that the filters are processed in parallel.  So when LP + BP + HP are summed, and if the  frequencies and levels are set correctly (as when the module is initialized to defaults), the input passes to output (nearly) unaltered.
