### ISSUE TITLE
Loading preset in stoermelder 8FACE causes crash

### ISSUE THREAD

**Issue by MaZe6K** [bogaudio/BogaudioModules#136]
Hello there!

I just had a few crashes with the newest Bogaudio version when I tried to use stoermelder STRIP with your ADDR sequencer. When I try to load a preset on STRIP, Rack crashes.
In the previous version it worked.

Windows 10, Rack 1.1.6, Bogaudio 1.1.34

**Comment by mdemanett** [comment]
I can't seem to crash it with STRIP, but can with 8FACE (based on [this](https://community.vcvrack.com/t/dark-mode-for-bogaudio-is-here/10757/14))...anyway it's probably the same problem.

This new [build](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test2) should fix it...if you have a chance to try it, please let me know if it does or not.

**Comment by MaZe6K** [comment]
ah I meant 8FACE, sorry... 
thank you, will try immediately

**Comment by MaZe6K** [comment]
it works now
when I load a preset on 8FACE it "flickers," it looks like it reloads the graphics each time I change the preset, but it works.

**Comment by mdemanett** [comment]
Cool, glad it works.
I had a fix for the flicker thing, but hadn't released it -- a build with that will show up [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test3).

**Comment by mdemanett** [comment]
This is finally released to the Rack library.
