### ISSUE TITLE
S&H number of outputs

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#138]
![afbeelding](https://user-images.githubusercontent.com/46076474/91085885-62581a00-e64e-11ea-99e0-fa4c153e6e9e.png)
Shouldn't the bottom one also be polyphonic ?

**Comment by mdemanett** [comment]
Indeed, will fix it.

**Comment by Petervos2018** [comment]
Fixed in 1.1.34, thanks Matt 👍
