### ISSUE TITLE
Feature Request: Expander for ADDR-SEQ

### ISSUE THREAD

**Issue by smok-e** [bogaudio/BogaudioModules#139]
Hi Matt,

would it be possible to add an expander to ADDR-Seq? 
It should just expand the steps of ADDR-SEQ to 16/24/32...
when you put the expansion module on the right of ADDR-SEQ.
It would work as the PGMR and PGMRX.
I did a mockup of how it could look ;-) the expander needs only 3hp.

![Bogaudio_Addr_Seq_02](https://user-images.githubusercontent.com/25061474/91643557-978caf80-ea34-11ea-86eb-f7771aa225d8.jpg)

jm2c

**Comment by mdemanett** [comment]
Definitely possible...I'll look into it.

**Comment by smok-e** [comment]
thank you Matt, it will be very appreciated.
