### ISSUE TITLE
Additator: Output not normalized

### ISSUE THREAD

**Issue by patman023** [bogaudio/BogaudioModules#14]
Win10/Rack 0.6.0 Release/ Bogaudio 0.6.6

At default initialized settings (changing only partials), Additator Outputs the following (as per Fundamental>Scope): 1: 30Vpp; 10: 18Vpp, 20 (default): ~15Vpp; 40: ~12.8Vpp 60: 11.6Vpp 100: 10.2-10.5Vpp

Even normalizing the output to half these numbers would be more reasonable.

**Comment by patman023** [comment]
For Reference, Fundamental outputs at ~10.8Vpp

**Comment by patman023** [comment]
Exactly. 

but blame the radio guy for checking his levels... ;-)

**Comment by mdemanett** [comment]
Fix finally released.  Thanks for heads up!
