### ISSUE TITLE
VCF and LVCF seem to run into rounding errors with lower sampling rates

### ISSUE THREAD

**Issue by hexdump0815** [bogaudio/BogaudioModules#140]
it looks like i discovered a similar problem with VCF and LVCF as i some months ago discovered with pErCO from bidoo: if used with low sample rates like 22.05khz (which i'm sometimes using on the sonaremin to reduce the cpu usage - you have to set it in the vcvrack settings file as 22050 as its not available from the menu) then something simlar happens like described here in the old pErCO issue: sebastien-bouffier/Bidoo#142 ... with VCF and LVCF i saw it at 22.05khz and when the frequency knob goes to the end - then the module at some point gets lost and can not be brought back to normal operation anymore ... please let me know in case you cannot reproduce it, then i can try to make the description more detailed ... it would be nice if it could be made working also for such low sample rates - maybe the bidoo solution gives a hint about how to fix it? here is a link to the bidoo fix: https://github.com/sebastien-bouffier/Bidoo/commit/20ac119df0db3180a8be5e12b2cd5643a0862506#diff-565b1fc20f1c6db5b3c26ec689dea88f

best wishes and a lot of thanks in advance - hexdump

**Comment by hexdump0815** [comment]
looking at the bidoo solution and trying to understand it (without really understanding the way the filter code works) i think there the cutoff frequency gets limited to 8khz to be at least smaller than half of the sample rate to avoid that the relation of the two cannot cross an unwanted border ... see also: https://github.com/sebastien-bouffier/Bidoo/issues/142#issuecomment-687868942

**Comment by hexdump0815** [comment]
looks like the original source of the clamping is the Fundamental VCF which does not show the problem - see: https://github.com/VCVRack/Fundamental/blob/v1/src/VCF.cpp#L149 ... i looked at the VCF and LVCF code and could not find the proper place (if it exists in here too) - i discovered a similar problem in MockbaModular's filtah and there the clamping helped to fix it too - see: https://github.com/MockbaTheBorg/MockbaModular/issues/13#issuecomment-687870124

**Comment by hexdump0815** [comment]
with this hack: https://github.com/hexdump0815/vcvrack-dockerbuild-v1/commit/552851e20bb8934a0b22a3ac9e8c2492c1197357 it works at 22.05 khz sample rate (i.e. it does no longer lock up), but looks like this has some side effects - for instance the frequency shown on right click of the frequency knob then is only half and i'm not sure wherever else this has influence - maybe with this the frequency range is only stretched from initially up to 20khz to only go to 10khz for the full knob range ... some kind of solution might be good as for v2 lower sample rates are available by default: https://community.vcvrack.com/t/rack-development-blog/5864/54

**Comment by mdemanett** [comment]
I fixed it to cap the internal cutoff frequency at 49% of the sample rate.  Knobs will still claim to be going up to 20khz.

**Comment by hexdump0815** [comment]
i can confirm that the fix is working - thanks a lot
