### ISSUE TITLE
Feature request: accurate Db readout in analyzers

### ISSUE THREAD

**Issue by squinkylabs** [bogaudio/BogaudioModules#141]
Since the lines are so far apart sometimes (24db?) it can get hard to get fine readings from the analyzers. Perhaps a display of the db range for the frequency(s) under the cursor? or an option of lines two or four times finer?

I know, it's always me, but I just use these things all the time....

**Comment by mdemanett** [comment]
I like the idea of showing the value under the cursor, will take a look.

**Comment by mdemanett** [comment]
Did this -- click and hold on any of the analyzers' displays, it will freeze and you get a details overlay box.

**Comment by squinkylabs** [comment]
Will try it out! tx.

**Comment by squinkylabs** [comment]
It works well. By its nature it's a little finicky trying to hit those peaks. It's super useful as is. I know it's a pretty esoteric feature - if there is some clever way to make it easier to query a peak it would be great. but super good feature already.
