### ISSUE TITLE
ADDR-SEQ and stoermelder 8face crash rack 

### ISSUE THREAD

**Issue by smok-e** [bogaudio/BogaudioModules#142]
I'm not sure where the bug is, but today I tried to use the 8face from stoermelder with ADDR-Seq
and it constantly crashes rack when I have assigned some "presets of ADDR-SEQ" to 8Face and want to change these
by a clock from CLKD.

I have done this before. without this issue.

I will post it at stoermelder too, because I don't know which module could be the cause of the issue.

I have 2 patches one with the bug, that uses ADDR-SEQ and one without the crash that uses ML-Quantum.

[8face bug_01.zip](https://github.com/bogaudio/BogaudioModules/files/5225929/8face.bug_01.zip)

[8face nobug_01.zip](https://github.com/bogaudio/BogaudioModules/files/5225933/8face.nobug_01.zip)

**Comment by mdemanett** [comment]
This was a crash on my side, not on stoermelder -- there's a fix, though it isn't on the library yet.  The [prerelease builds here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test3) have the fix.

**Comment by smok-e** [comment]
thanks for fixing it !!!
