### ISSUE TITLE
Unison not working?

### ISSUE THREAD

**Issue by Ledarium** [bogaudio/BogaudioModules#143]
I am not sure I got Unison mode quite right, but when I turn on detune with two channels, I should hear two frequencies and get two peaks on spectrum analyzer. But it is not working, with any amount of detune and any number of channels. Am I missing something?

![2020-09-19_21-41](https://user-images.githubusercontent.com/10389237/93686782-52065400-fac1-11ea-9c40-8b29850098c5.png)

Anyway thank you for awesome modules!

**Comment by Petervos2018** [comment]
Hi ,
the unison is working with cv not audio.
So the v/oct goes into unison, and the v/oct out from unison goes to the wave module v/oct in.
And the out of the wave module goes to the mixer.
![afbeelding](https://user-images.githubusercontent.com/46076474/93687241-5e3be280-fabc-11ea-92ff-7ff6d3e5f2ca.png)

Hope this helped.

**Comment by Ledarium** [comment]
@Petervos2018 Nice, thanks. Missed obvious `V/OCT` label :+1:
