### ISSUE TITLE
Module Request - VCA Matrix

### ISSUE THREAD

**Issue by VegaDeftwing** [bogaudio/BogaudioModules#144]
You've already got VCAs, you've already got Matrix mixers, Think you could do a VCA Matrix similar to the one from 4ms? 

![VCAMatrix](https://www.modulargrid.net/img/modcache/2094.f.jpg)

The 4ms vca matrix also is chainable but I think without the constrains of a physical system you could make something that has a much more elegant UI if you were to include expanders. Possibly an 8x8 with the mutes and knobs at the side would make expanders a moot point though, as I can't imagine anyone even being able to practically use anything bigger.

I already have this module in hardware and can vouch for it's usefulness. The real-deal does some nice sounding (soft?) clipping when signals get too hot, which is obviously easy to do given it's regularly used for feedback systems. Given I've seen VCV get weird with signals getting too hot before this may be a good addition depending on the CPU overhead.

**Comment by Petervos2018** [comment]
Hi, just a heads up : 

https://library.vcvrack.com/dBiz/VCA4

![afbeelding](https://user-images.githubusercontent.com/46076474/93995810-c37c2600-fd91-11ea-90fc-b26ed41d01e4.png)

**Comment by VegaDeftwing** [comment]
Hmm, yeah. I'll still leave this up in case mdemanett is still interested in it or a variation that either has expanders or one that's made by just expanding Matrix44/88 ¯\\_(ツ)_/¯

**Comment by Petervos2018** [comment]
I just wanted to point out there was something similar...
Still a good idea, maybe Matt wants to do something with it.

**Comment by mdemanett** [comment]
I could see making CV expanders for 44/88....

**Comment by mdemanett** [comment]
I went ahead and made these...there's a [test build](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test6) available.  Prerelease docs [here](https://github.com/bogaudio/BogaudioModules/blob/master/README-prerelease.md).

@VegaDeftwing you mentioned soft clipping -- for the record these do that by default (it can changed to hard clip on the context menu).  It's surely not as nice as the analog hardware.

![Screen Shot 2020-10-05 at 11 28 37 PM](https://user-images.githubusercontent.com/49971/95155850-0e6b4580-0763-11eb-9c62-69e9c80de35a.png)

**Comment by VegaDeftwing** [comment]
Ran both through their paces, seem to work great! Only thing I can think that might be nice is a right click option to set the mute matrix to the identity matrix or inverse of identity matrix, but that's a minor thing. Thank you for making this
