### ISSUE TITLE
static constexpr member problem with c++11

### ISSUE THREAD

**Issue by Nowhk** [bogaudio/BogaudioModules#145]
Hi,

I think you need to include:

```
constexpr float ChirpOscillator::minFrequency;
constexpr float PureChirpOscillator::minFrequency;
```

to `oscillator.cpp` file, else it won't compile using c++11.

**Comment by mdemanett** [comment]
Yep done.

**Comment by Nowhk** [comment]
Nice, thanks :) 
May I ask here (since I'm not able to contact you via FB) how you include your math.hpp in the project?
If I try to do so for some my files, It conflicts with the alteady math.hpp by Rack.

I use pragma once like you, but it fails. Some tricky flag to compiler?

Hope you can help me:) thanks

**Comment by mdemanett** [comment]
Hey, I've never run into a problem with those clashing, but that might be luck.  I only include "rack.hpp", which itself includes rack's math.hpp, which maybe has something to do with it.

**Comment by Nowhk** [comment]
Yes I do the same, but math from rack and my math file don't work together, of course they are the same name :O I'll investigate. Let me know if you find somethings related. Thanks
