### ISSUE TITLE
Bogaudio LFO (big knob) and 8face Stoermelder

### ISSUE THREAD

**Issue by Gstyle11** [bogaudio/BogaudioModules#149]
Causing crashes when switching between 8face scenes on Mac osx Mojave when using together.

On Windows 10 works ok, but causing
Color shifting to dark when using 8faces scenes

**Comment by mdemanett** [comment]
There is a fix for that, but the fix isn't released to Rack yet.  Just install a test release from [the releases page](https://github.com/bogaudio/BogaudioModules/releases) and you'll be set.

**Comment by Gstyle11** [comment]
Hi first thank you so much for  the wonderful bog modules.
Thank you for this info

**Comment by mdemanett** [comment]
Fix is released to the Rack library.
