### ISSUE TITLE
ADDR-SEQ: Steps knob, snap?

### ISSUE THREAD

**Issue by isabelgk** [bogaudio/BogaudioModules#151]
Hi Matt,

I was wondering if the snapping mode on the STEPS knob of ADDR-SEQ used to be on? I feel like I remember it being a snappy knob, but latest version (v1.1.35) seems to be continuous. (Same for the SELECT knob.)

**Comment by isabelgk** [comment]
Ah, I see this might be because of the expander?

**Comment by mdemanett** [comment]
> Ah, I see this might be because of the expander?

Yep, exactly.
