### ISSUE TITLE
Feature request RGate: save output range setting + 0V output when idle

### ISSUE THREAD

**Issue by Deevje** [bogaudio/BogaudioModules#153]
Hey Matt,

I'm having a lot of fun with the frequency division and multiplication possibilities of the RGate module, especially the gate length/PWM feature, the only issue I'm having is that I have to change the output setting to the desired +/- 5V for audio purpose every time I open Rack.

As it is now, every time a patch with the RGate is opened, or even when Rack is closed and opened again, the RGate's output setting goes back to the default 0-10V, which makes for a nasty DC offset and weird pops and clicks in the sound.

Then I was wondering if it were possible to have a 0V output when no input is received, so that, when used for audio purposes, there is no DC offset when there is no audio coming in (I've noticed this to be a problem sometimes when playing guitar through it, needing a filter to counteract the DC offset)

I hope that at least the first request is possible to implement, the second one I could imagine is a bit more tricky but would still be awesome.

Thanks as always for your ever expanding awesome collection of modules, I find myself using many of them a lot!

Cheers!
Deev

**Comment by Petervos2018** [comment]
`As it is now, every time a patch with the RGate is opened, or even when Rack is closed and opened again, the RGate's output setting goes back to the default 0-10V`

I think it's a bug, the settings are not recalled correctly.

**Comment by mdemanett** [comment]
A bug yes, thanks for pointing it out.  A test release with the fix is here: [v1.1.35-test1](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test1)
