### ISSUE TITLE
NSGT Knee Switch bug (behave like a mode switch in PRESSOR)

### ISSUE THREAD

**Issue by sandyadr** [bogaudio/BogaudioModules#154]
I don't know if it is a bug in NSGT or it's supposed to be like this, I already read the manual and I found that the switch supposed to do the same job as in PRESSOR.

But when I change the knee switch to hard in NSGT, the module act like a compressor rather than a noise gate (I tried to gate the background noise in my mic input BTW). Then I tried to do the same job in PRESSOR and it works like I thought it would be (work as intended), the knee switch makes the knee soft/hard. 

Then I compare the two modules with the same input and setting (except for the attack time and release time and other PRESSOR only parameter), and I realize that the knee switch in NSGT behaves like a mode (comp/gate) switch in PRESSOR.

Is it a bug or it is designed to works like that? I'm using the latest version in the library (1.1.35) when I realize that it may be a bug, and tried the latest beta (1.1.35-test1) too.

Thx in advance and sorry for my messy English, as it's not my main language 😀

**Comment by mdemanett** [comment]
This was a pretty bad bug, thanks for pointing it out!  I added a new [test release with the fix](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test2), if you want to give it a try.

**Comment by sandyadr** [comment]
wow! that was quick 😮

Already tried the test release, and it behaves correctly now, thx for the fix Matt!

Slightly out of topic and not a bug, but unfortunately, after I compare the result with the PRESSOR, it seems that the fixed release time in NSGT is quite slow (around 1s if I hear it right) for my needs, so I'm still using the PRESSOR gate in the end.

And if I may request for a feature/enhancement (should I create another post for it?), is it possible to lower the limit of the threshold in NSGT/PRESSOR? I know that -24 dB is quite enough for a compressor, but for a gate (especially a noise gate from external mic), -24 dB is quite high, it would be great if the threshold is at around -36 dB, I guess.

**Comment by mdemanett** [comment]
These are great suggestions, thank you.  It is easy to extend the threshold down to -36db, and NSGT can get attack and decay controls on the context menu.

**Comment by sandyadr** [comment]
My Pleasure! Can't wait for the next update, I liked the sound of it. 

Yes, -36dB is a reasonable amount for this module (even though I interpreted it more as a (downward) expander rather than noise gate, after reading your description in the manual and the control it provided, but maybe XPND not as catchy as NSGT😃), as a lot of noise gate hardware/plugins sometimes provides down to -48dB or even lower only for battling with noise from SNR.

Thx again for the fix and planned updates!

**Comment by mdemanett** [comment]
It took a while, but a [test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test3) is available now, with context-menu sliders for attack and release in NSGT (and LMTR), and a menu option to double the threshold range in dB on all four of the dynamics modules (so it will go down to -48dB).

**Comment by sandyadr** [comment]
Great, I'd like to try this update, is there any pre-built package for this test-release?

**Comment by mdemanett** [comment]
There were supposed to be, but it didn't work; they're here instead: https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test4
