### ISSUE TITLE
Module Request: Sample Based ADSR

### ISSUE THREAD

**Issue by VegaDeftwing** [bogaudio/BogaudioModules#156]
I really like the XAOC Zadar but there's nothing quite like it in VCV. I've been thinking about the best way to do this for months now, and while I don't think I have the programming chops to do it myself, I think I've thought though it enough to come up with a way of making it that is at least feasible. The Zadar is more wave-table based, but I don't think that's strictly necessary or the best way to do it. Instead, I think being able to set a different .wav file to each stage would work better.
So, I was thinking something like this:
![adsrreq](https://user-images.githubusercontent.com/11283620/99575827-c4e75a80-299e-11eb-90d5-75028e1a8f9a.jpg)
Alright, so, some explanation necessary here-

Basically, this would just be a normal ADSR where each stage get's AM with a sample. I think it'd be useful to provide both the 'clean' ADSR out and the sample-modulated (complex) adsr out. The complex ADSR output would likely need a filter, as often modulation needs to be kept somewhat lower-frequency.

Each .wav would just need to be time stretched to match the time set by the A,D, and R knobs. That's why I didn't draw on a CV control over the stages, the time would effectively be fixed when each stage starts to avoid needing to live-stretch the sample. Sustain couldn't have it's time determined before hand, so it makes more sense to just specify that the sample would just loop. This of course has an issue of forcing zero-crossings, so it would likely have to extend the sustain stage to last until the first 0-crossing after the end of the sustain sample.

The big knobs next to each sample would be simple attenuators to change how much AM each sample does, with the smaller knobs being attenuverters that route the simple-ADSR output as self modulation onto this AM depth. I think having the complex out modulate this would get too crazy too quickly.

I did my best to keep this similar-ish to DADSR(H)+, but obviously there's a fair amount of extra stuff going on here. I thought I'd ask you first as the design I have in mind is based off of your work, but if you're not interested I can go post it in the VCV forum. 

It may be useful for it to look for files following a naming scheme in a folder to load all 4 samples at once, maybe just loading a.wav, d.wav, s.wav, and r.wav if they exist in a folder?

**Comment by mdemanett** [comment]
Interesting idea...I don't think there's anything quite like it.  But I won't have bandwidth to look into it anytime soon.  Go ahead and see who's interested, no concerns on my end.

**Comment by VegaDeftwing** [comment]
Still been thinking about this, and I think I came to the conclusion that what would work even better than sample loading would just to have a per-stage ring mod. This would even mostly fit into the current panel design for DADSR(H)+ just instead of CV over each stage's length/level it would just ringmod each stage with a different input. The only awkward part would be waiting for the ringmod input to go through a zero crossing before going to the next stage. I never did get around to posting this into the forum but will soon if you're not up for it.

**Comment by mdemanett** [comment]
Hey sorry to not get back to you.  But I don't think I get what per-stage ring mod would mean.  Seems like a good one to hash out in the forum.

**Comment by VegaDeftwing** [comment]
already did https://community.vcvrack.com/t/adsr-with-per-stage-ring-mod/12115 - looks like KautenjaDSP may go for it.
