### ISSUE TITLE
Feature Request: Slow mode for SLEW

### ISSUE THREAD

**Issue by grncdr** [bogaudio/BogaudioModules#158]
Hey, thanks for all these amazing modules!

What do you think about adding a "SLOW" toggle to the slew limiter (similar to the ones on LFOs)? I find myself needing to fall back to the Befaco slew limiter for certain effects because the maximum time for the Bog Audio one is a bit too short.

**Comment by mdemanett** [comment]
Interesting, yeah, I can look into that.

**Comment by mdemanett** [comment]
A [test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test3) is now available with this change.
