### ISSUE TITLE
LMTR not tagged properly

### ISSUE THREAD

**Issue by bram2000** [bogaudio/BogaudioModules#159]
Hello!

LMTR doesn't seem to be tagged properly with the `Limiter` tag. It shows in the tooltips, but not if you filter to the `Limiter` category. I cannot even find it by searching for the word "Limiter" which seems really odd as the exact string is visible in the tooltop.

Thanks.

**Comment by mdemanett** [comment]
Hey, thanks for noticing that, I'll fix it for the next release.  With the tag it will also show up in the search.
