### ISSUE TITLE
Ratio knob on FM operator

### ISSUE THREAD

**Issue by WouterSpekkink** [bogaudio/BogaudioModules#16]
Hi, thanks for some great modules! I have a question about the FM operator. The main frequency knob is described as a knob calibrated for setting the frequency as a ratio of the frequency dictated by the V/OCT input. Furthermore the readme states that you can set the relative frequency of each operator via ratios.

However, the default value of the frequency knob is 0, which is in itself a bit confusing if we are using the knob to set ratios. Should the default value not be 1? 

For example, if the input of the V/OCT is 100hz then this means (if I understand the functioning of the module correctly) that 100hz translates to a value of 1 in the denominator and numerators of the ratio, and by setting the knob to a value of 5, we set a ratio of 5/1, and therefore set the frequency to 500hz in this case. Setting the knob to a value of 0.5 sets a ratio of 50hz, and so on. A ratio of 0/1 does not seem to make sense in this case.

If I am correct in this, then I also think that the ticks of the dial of the frequency knob need to be adapted. There are currently 4 ticks in between the option 0 and the option 5, and presumably these stand for values of 1, 2, 3 and 4. However, if the current 0 option is actually 1, then having four ticks does not make sense (there should be 3 evenly spaced ticks in between the default setting and the setting of 5). 

EDIT: Another reason why the default option of 0 is confusing is that according to the labels the range of the knob currently goes from 0.1 to 0.5 (increasing the value), then from 0.5 to 0 (decreasing the value), and then from 0 to 10 (increasing the value), while in reality turning the knob left decreases the frequency and turning the knob left increases the frequency of the oscillator.

**Comment by mdemanett** [comment]
Agreed, the zero should be a one.  Will fix next release.

**Comment by WouterSpekkink** [comment]
Thanks! Also, I would take a look at where the ticks of the dial should be
located. I checked with the hottuna module by NYSTHI, and all ticks seem to
be off. For example, the ratio of 5:1 seems to be a bit before its actual
tick.

**Comment by mdemanett** [comment]
Fixed in new release.

**Comment by WouterSpekkink** [comment]
Awesome. Thanks again!
