### ISSUE TITLE
FM-OP Issue

### ISSUE THREAD

**Issue by michellewalbeck** [bogaudio/BogaudioModules#161]
Hi,

I might be doing something wrong. I'm having an issue with the FM-OP module. The ADSR does not seem to respond to an external gate input, nor does it respond when just turning the knobs "by hand". It currently just plays a note continuously. It does respond to v/oct input and I'm controlling feedback with velocity. The ADSR has no effect in any way on what is played. 

Thank you for your time.

**Comment by michellewalbeck** [comment]
I'm having the same issue with other synth voices, so I'll investigate what I'm doing wrong. Thanks anyways! :)

**Comment by Petervos2018** [comment]
For the env to work you need to turn it on (see green circle)

![afbeelding](https://user-images.githubusercontent.com/46076474/103363033-6db6c880-4aba-11eb-9502-e035e17871c6.png)

**Comment by michellewalbeck** [comment]
Thank you for the reply. I'm trying to control with a Beatstep Pro. The BSP seems to be the issue. When I use the Qwerty Keyboard everything works as expected.
