### ISSUE TITLE
Analyzer::processChannel()

### ISSUE THREAD

**Issue by pronvit** [bogaudio/BogaudioModules#163]
`Analyzer::processChannel()` and `AnalyzerXL::processChannel()` should be `processAll()`, shouldn't they?

**Comment by mdemanett** [comment]
Yeah, that'd be better style.  Functionally, _channels is always 1 in those modules, and processChannel() and processAll() are both called exactly once per sample.  I added processAll() at some point and didn't go back and change existing things.

**Comment by pronvit** [comment]
Oh right, sure. Anyway, just wanted to let you know.

**Comment by mdemanett** [comment]
Thanks for pointing it out, will clean it up.
