### ISSUE TITLE
Request: Polyoff mode where offset isn't scaled

### ISSUE THREAD

**Issue by SergeProtectorMusic** [bogaudio/BogaudioModules#164]
Would it be possible to make a mode of Polyoff where offset is absolute, not scaled? It would be really handy for velocity control to be able to do things like e.g. having an absolute offset of 6 volts and 40% scaling, so you could turn a 0-10 volt velocity signal into 6-10 volts. 

Thanks for all the great modules!

**Comment by mdemanett** [comment]
Makes sense.  This is basically the same request as for the regular OFFSET module [here](https://github.com/bogaudio/BogaudioModules/issues/160)...change it to scale, then offset instead of offset then scale.  I'll take a look.

**Comment by SergeProtectorMusic** [comment]
> offset

Good call. I missed that.

**Comment by mdemanett** [comment]
A new [test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.35-test3) is available with this change...same caveats as with [OFFSET](https://github.com/bogaudio/BogaudioModules/issues/160).
