### ISSUE TITLE
LFOS need rate mod input

### ISSUE THREAD

**Issue by XtremeSounds** [bogaudio/BogaudioModules#165]
HI I can use uMAP  to do this but it would be cool if we cool patch in a mod to the lfo rate.  Even having the lfo out go back to modify itself might be cool.  Maybe we could just get a new lfo altogether for this purpose. 

It would be cool if we had an lfo and and adsr combo as one module to create random waveforms

**Comment by mdemanett** [comment]
All the LFOs have a v/oct input, which is CV for the rate.

**Comment by XtremeSounds** [comment]
Ok thanks I must have missed it somehow.  Still learning…

**Comment by XtremeSounds** [comment]
Thanks again.
