### ISSUE TITLE
CLPR is not tagged properly

### ISSUE THREAD

**Issue by jamshark70** [bogaudio/BogaudioModules#167]
Similar to #159 -- I was looking for a control voltage clipper. I typed in "clip." No results appeared.

After complaining on the Facebook group, I was told that the module's name is clpr.

I would not have guessed that.

I can't imagine this is intentional. Hope it can be fixed in the next release (as I spent about an hour searching through different module types, and even considered building it myself in Prototype, where I would have had the answer in seconds if the module had been searchable).

**Comment by mdemanett** [comment]
I added "clipper" to the module display name to make it searchable -- Rack v1 doesn't have a "clipper" tag, and doesn't search module descriptions.  Rack v2 might fix this.

**Comment by jamshark70** [comment]
Ok, thanks for this. I didn't know descriptions don't get searched 😢 since the change is committed, I'll close this. Cheers --
