### ISSUE TITLE
Possible crash related to "Analyzer" when disabled

### ISSUE THREAD

**Issue by philippesalembier** [bogaudio/BogaudioModules#169]
Hello,

Since the last update (v1.1.36) I am experimenting quite a few crashes apparently related to the analyser. Here is a typical log:

19: 1 Rack 0x000000010fb4723d _ZL18fatalSignalHandleri + 45
18: 2 libsystem_platform.dylib 0x00007fff6f6955fd _sigtramp + 29
17: 3 ??? 0x0000000000000009 0x0 + 9
16: 4 libsystem_c.dylib 0x00007fff6f56b808 abort + 120
15: 5 libsystem_c.dylib 0x00007fff6f56aac6 err + 0
14: 6 plugin.dylib 0x0000000013554a21 _ZN8bogaudio15AnalyzerDisplay4drawERKN4rack6widget6Widget8DrawArgsE + 1297
13: 7 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
12: 8 Rack 0x000000010fb724ac _ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE + 92
11: 9 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
10: 10 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
9: 11 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
8: 12 Rack 0x000000010fbac54f _ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE + 111
7: 13 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
6: 14 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
5: 15 Rack 0x000000010fba7fe4 _ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE + 52
4: 16 Rack 0x000000010fbac267 _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 343
3: 17 Rack 0x000000010fb5f6ba _ZN4rack6Window3runEv + 1386
2: 18 Rack 0x000000010fb46d6a main + 1450
1: 19 Rack 0x000000010fae0034 start + 52
0: 20 ??? 0x0000000000000001 0x0 + 1

I am on a Mac and I think this is related to cases where the Analyzer has been "disabled" (Cmd+E) in the patch.
The crash occurs when one tries to load a patch saved with the Analyzer in the disabled mode.

Thanks in advance... and thank you very much for your wonderful modules!

**Comment by mdemanett** [comment]
Yes, confirmed, thank you for reporting it!  Fixed builds are [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37), and I'm requesting a new community build, that'll be up in a couple days.

**Comment by philippesalembier** [comment]
Great. Thanks for everything!
