### ISSUE TITLE
Level inputs in MIX8

### ISSUE THREAD

**Issue by jponsford** [bogaudio/BogaudioModules#17]
Hi Matt, I find your modules some of the best out there for what I'm trying to do with Rack. In particular, they're very very functional, with an impressively low appetite for CPU.

I noticed an issue with MIX8 the other day, and just had a chance to verify it today: it seems like the level inputs on Ch 5-8 do not respond to CV to change the volume output.

Thanks! and I appreciate all your amazing work!

**Comment by mdemanett** [comment]
Oops -- confirmed.  Will fix in the next release.  Thanks for the heads up!

**Comment by mdemanett** [comment]
Fixed in new release.
