### ISSUE TITLE
Module request, "dual gate/trigger input" switch

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#172]
Hi Matt, excuse me for the quick mockup.

![Multi-input switch](https://user-images.githubusercontent.com/40998416/112765329-fe933680-900c-11eb-8342-afaad776f399.png)

Could you please consider creating a dual input trigger switch like this, so 2 trigger/gate inputs could control the switch?
Priority for the trigger/gate that comes in first.

**Comment by mdemanett** [comment]
Can you just "or" the inputs with a logic module, like this, or are you looking for a different behavior?

![Screen Shot 2021-03-28 at 8 00 04 PM](https://user-images.githubusercontent.com/49971/112772769-a3f3dd80-9000-11eb-8257-908d2e3d570d.png)

A combo logic/switch is a great idea though, will look into it.

**Comment by Eurikon** [comment]
Hi Matt, yes this is the behaviour i was after from within 1 module. 
I wanted to minimise the clutter of more modules, therefor was hoping to have it in 1 module. 
Maybe in time there can be more ideas to make such a module more interesting.

Thanks for your time as always :)

**Comment by mdemanett** [comment]
I got this done:

![Screen Shot 2021-04-15 at 11 36 26 PM](https://user-images.githubusercontent.com/49971/114967988-70f47b00-9e43-11eb-8e1b-edc09ea1dadf.png)

Available in the test builds [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test1).  Documentation [here](https://github.com/bogaudio/BogaudioModules/blob/v1.1.37-test1/README-prerelease.md#-lgsw).

**Comment by Eurikon** [comment]
Awesome Matt! Thanks a lot :) 

Will try it after the weekend!

Cheers, Latif

**Comment by Eurikon** [comment]
Checked, works fine for me! Thanks again Matt :)
