### ISSUE TITLE
ADDR-SEQ: SELECT CV input doesn't wrap around based on STEPS knob

### ISSUE THREAD

**Issue by maartenschumacher** [bogaudio/BogaudioModules#173]
I'm a beginner at VCV so let me know if I'm going about this the wrong way or have the wrong expectations.

**What I'm trying to do**
I want to play a 5 step sequence at 5 different speeds, and each voice should start at a different point in the sequence.

**What I tried**
I configured the sequence and turned the STEPS knob to 5. Then added a 5-channel polyphonic input to CLOCK, to control the different speeds. Then added a 5-channel polyphonic input to SELECT CV to make each channel start at a different step.

**What went wrong**
When adding a constant voltage to SELECT CV, the steps wrap around after step 8, no matter what the STEPS knob is pointing to. Meaning my last voice goes 5-6-7-8-1 instead of desired 5-1-2-3-4. This is different from the behavior when adjusting the SELECT knob, in which case it wraps around after the amount of steps configured by STEPS knob.

I expected the CV input to have the same behavior as the knob here, is it possible to change?

Thank you for the great modules 🙏

**Comment by mdemanett** [comment]
It may be a bug, I'll take a look....

**Comment by mdemanett** [comment]
I didn't find a bug, it was working as intended, where select offsets the range of the steps.  But that behavior isn't what you're looking for, and what you're describing seems legit and handy to me.  So I added mode "Wrap select at steps".  Toggle that on and it should do the right thing.

Test builds are available [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test1) if you'd like to try it.

**Comment by maartenschumacher** [comment]
Great! Thanks :)
