### ISSUE TITLE
Incorrect label on PEQ14 Freq Pots.

### ISSUE THREAD

**Issue by ruchg** [bogaudio/BogaudioModules#174]
When moving from left to right, hovering over the **PEQ14**  FREQ pot, a popup shows the Channel number and the Frequency.

Each pot displays the corresponding Channel number until you get to Channel 7, which displays Channel 6.  All the channels higher than 6 all display Channel 6.
[PEQ14Edit.pdf](https://github.com/bogaudio/BogaudioModules/files/6274483/PEQ14Edit.pdf)

**Comment by mdemanett** [comment]
Yep, good catch, thanks.
