### ISSUE TITLE
PEQ14XF only works when a parent module output is patched

### ISSUE THREAD

**Issue by ddelabru** [bogaudio/BogaudioModules#175]
I used PEQ14XF with a PEQ14 module (even though the manual says it's an expander for the PEQ6 module). The only thing I wanted to use this particular PEQ14 module for was the 14-channel envelope followers, which I was feeding into the channel level controls of another PEQ14 to make a vocoder. The problem is that the envelope followers of the PEQ14XF would only produce a steady 0v, even when I monitored the PEQ14 input signal to make sure it was good and adjusted the expander module's gain to maximum and dampening to minimum. Then I connected a patch cable to the main output of the parent PEQ14 module to determine if anything was getting through that and suddenly all the envelope follower outputs came alive. Patching just the ODD or EVEN output of the parent module also seemed to work. But if none of those outputs were patched, the envelope followers became inactive again.

**Comment by mdemanett** [comment]
That's a bug, thanks for catching it.  The module shuts down internally if no outputs are connected, to save CPU when it's just sitting there.  But it should check the expander outputs as well.
