### ISSUE TITLE
There is a lot of DC on the VCO outputs

### ISSUE THREAD

**Issue by squinkylabs** [bogaudio/BogaudioModules#176]
The pulse waveshape outputs a lot of dc. It behaves like simple arithmetic tells you it will - at narrow pulse widths there is significantly more DC than signal on the outputs.

Luckily for you you don't have the MinBLEP bug that adds a small amount of DC to sawtooths.

FM, of course, can output some DC when the modulation is high. For now I'm not worrying about that on my FM VCOs.

**Comment by mdemanett** [comment]
I've seen that but didn't think much about it.  Is it a typical solution to just compute the offset and subtract it from the output?

**Comment by squinkylabs** [comment]
that's what I do. I think that is better and cheaper than a filter. Some VCOs that model analog stuff put a HPF on the output. Ironicly, Fundamental in "digital" mode puts out a ton of DC, but in "analog" mode it doesn't.

This actually threw me for a loop - I filtered a signal very heavily with an LPF, then tried to boost it back up with a compressor, but my compresssor saw all the DC and decided it was "loud" already. I thought my filter was broken, but but was just dc on the fundamental VCO (his analog saw also has a lot of DC, which is pretty common).

**Comment by mdemanett** [comment]
Oh, I never thought about what this would do to a compressor.  Thanks for the lessons!

**Comment by squinkylabs** [comment]
I had forgotten, actually. A year or two ago I got busted by a "customer" who pointed out the my Cheybshev output a lot of DC - I have never really thought about it. I head to search the internet for a good half hour to find out what the integrals of the Chebyshev polynomials. I can't do that much math without making a bunch of mistakes.
