### ISSUE TITLE
Linear interpolation weirdness

### ISSUE THREAD

**Issue by Nowhk** [bogaudio/BogaudioModules#177]
Looking at this code: https://github.com/bogaudio/BogaudioModules/blob/ad1e324f7eaebfa6c6ed04ad853b2a0261883603/src/dsp/oscillator.cpp#L70

You mod i if higher than tableLenght, but not fi. 
Ex. What if tableLength is 512, fi = 514,34. You will than have i = 2, and if you don't mod also fi, interpolation frac part become (fi - i) = 512,34 (not normalized anymore).

**Comment by mdemanett** [comment]
You're correct.  Thanks for pointing it out!

**Comment by Nowhk** [comment]
> You're correct. Thanks for pointing it out!

Ohh nice :) Thanks

Further question: why do you move now phase %= cyclePhase also for tableLenght >= 1024? Wouldn't the integer math do it automatically later? Isnt' useless? 

I mean, in terms of optmization :)

**Comment by mdemanett** [comment]
> Further question: why do you move now phase %= cyclePhase also for tableLenght >= 1024? Wouldn't the integer math do it automatically later? Isnt' useless?

I thought it clarifies the intent / makes it more obvious what's going on, and also makes it consistent with some other functions in the file that do the same thing.  Or maybe it just feels right. :)
