### ISSUE TITLE
matrix88 option for knobs only from 0 to 100

### ISSUE THREAD

**Issue by matthleg** [bogaudio/BogaudioModules#178]
Hello,
First thanks for your great modules, it's almost impossible to use vcv without using them.
As I am using matrix88 I don't need the negative range of the knobs and for me it is just complicating the manipulation in "live time". So I would love to have in the right click menu an option to have the knobs limited from 0 to 100. Please think about it, and thanks a lot again.
Have a nice day,
Matthieu

**Comment by mdemanett** [comment]
Yeah, makes sense, I'll look into it.

**Comment by mdemanett** [comment]
This is implemented in the [latest test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test2).

**Comment by matthleg** [comment]
Thanks a lot it's perfect.
It would be nice if you can **do the same** with expander: **MX88CV**
Have a nice week-end.
Matthieu
