### ISSUE TITLE
Mixer modules' level CV curve seems... strange

### ISSUE THREAD

**Issue by jamshark70** [bogaudio/BogaudioModules#179]
I have a question about the level CV curve in the Bogaudio mixers.

Here, I've set up the same oscillator going into a Fundamental VCA, and a Bogaudio Mix4. Both have the same Manual CV connected to the level CV input, and both modules' GUI level faders are set to 0 dB.

With 10V into the CV input, the output levels are identical (-6 dB). (Also, with 0V, both modules output silence, but that's trivial, so I won't bother to screenshot it.)

![levels-10V](https://user-images.githubusercontent.com/318301/123585911-8ceaa480-d816-11eb-8f3b-c4f52eff78d0.png)

At 5V, Fundamental VCA has dropped to -12 dB while Bogaudio has dropped (AFAICS) to -36 dB (inaudible at low volume).

![levels-5V](https://user-images.githubusercontent.com/318301/123585938-96740c80-d816-11eb-9b15-01f79e2206b6.png)

The use case here is a large, collaborative patch, where layers need to be enveloped. Because the patch is very large and is already pushing CPU limits, I don't want to add half a dozen VCAs -- I would rather just plug the envelopes into the mixer. But Mix4 seems to require some special handling for this (i.e. for this patch, I might have to take out Mix4 where the students used it, and substitute a different mixer).

I'm guessing that VCA is going by amplitude -- half voltage = 6 dB attenuation (which is perhaps too naive an approach in itself, since low voltages may have a hair-trigger effect on volume while high voltages are less sensitive) -- while Bogaudio maps voltage onto dB. But the latter approach seems not ideal, perceptually: the middle of the voltage range is really too quiet to be useful (so, low input CVs are effectively inaudible). It would be nice if there were a RMC-menu option to choose the level CV mapping formula. (Edit: Some resources recommend a 'squared' formula, e.g. `(cv_input / 10).squared` so that 5V --> 12 dB attenuation.)

**Comment by mdemanett** [comment]
You're right about what's going on, Fundamental VCA has a linear-in-amplitude CV response, whereas MIX4 is linear-in-decibels (I think toggling the switch on VCA to EXP will make it linear-in-decibels, but haven't checked).  

My VCA is linear-in-decibels (same as MIX4) by default, but has a LIN button that makes it linear-in-amplitude.  Adding the same linear mode to the mixers would be easy.  I'll think about a squared or other modified response as well.

**Comment by mdemanett** [comment]
The linear-level mode is implemented in the [latest test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test2).
