### ISSUE TITLE
S&H not normalizing to white noise

### ISSUE THREAD

**Issue by benirose** [bogaudio/BogaudioModules#18]
I saw in the docs that the S&H module normals to internal white noise if nothing is in the input, but I'm not getting anything in my scope until I hook up a noise source to the input. I'm on 0.6.2b. Would love to use this awesome tiny module for all my S&H needs!

![image](https://user-images.githubusercontent.com/2953531/45248857-9b254a00-b2e4-11e8-9b71-c755be6f2c7a.png)

![image](https://user-images.githubusercontent.com/2953531/45248858-a24c5800-b2e4-11e8-964a-7df6f5836eb8.png)

**Comment by mdemanett** [comment]
Hey, thanks for the report and the screens.

Your first patch should work.  However I see that it doesn't with the version of Bogaudio on the plugin manager in Rack 0.6.2b -- I think the plugin was built against 0.6.1 and there's a slight incompatibility that's causing this.

So, this should be fixed next time I release and get a build update.  That should be next week sometime.  If you know how to build plugins and install from source, that'd be a way to fix it now, most likely.

**Comment by benirose** [comment]
Awesome thanks for looking into this! I do know how to build plugins but I’m trying to keep as much in the manager as possible so I can wait a week! I’m a big fan of the 3hp modules made, keep em coming!

**Comment by mdemanett** [comment]
I finally got a new release out -- and it didn't fix this.  Will try again....

**Comment by benirose** [comment]
Zangit! I appreciate you keeping the ticket open and updated!

**Comment by mdemanett** [comment]
I finally found the problem -- it's fixed in the new release.
