### ISSUE TITLE
OFFSET : Order of Operation - wrong default value  (old patches)   

### ISSUE THREAD

**Issue by Outboarder** [bogaudio/BogaudioModules#180]
Today I opened some of my old patches they all sounded differently, after some trial and error I found the problem.
Offset module default entry for (order of operation) should be (offset then scale) but it sets as (scale then offset).
I don't know which update caused the issue, hope it is the recent one!

**Comment by Petervos2018** [comment]
Hi maybe look here : 

https://github.com/bogaudio/BogaudioModules/issues/160

There is a right-click option for it now.

**Comment by Outboarder** [comment]
so, I have to manually change that in every patch, I can do that : )

**Comment by mdemanett** [comment]
Yep, that's the solution.  Sorry about that!
