### ISSUE TITLE
S&H smoothing

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#181]
Hi Matt how are you doing, 
wish you are well!

Can we please get a slider control in the S&H module context menu that allows for smoothing the output. 

On many occasions where i use the sh module (nearly every patch)to control CV inputs, i might run into tick/clicks in the sound later on. Where i then i have to start and add vcf or slew to smooth a bit until the clicking is fixed. 

Would be very useful if i could set the smoothing from the module itself and reach everything that is connected at once.

Hope this makes sense :) 
Thanks!

**Comment by mdemanett** [comment]
I like it, will look into it.

**Comment by mdemanett** [comment]
Just made one: https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test3

**Comment by Eurikon** [comment]
sweet!
