### ISSUE TITLE
LVCO wave micro fade

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#182]
Hi Matt, 

i sometimes control the wave switch of this module to quickly switch from wave to wave, which results in nice unique sounds (with uMap Stoermelder).   
This does however introduce some slight clicks. 

Is it possible to have a sort of either micro delay/fade between the switching, or micro cross fade between the switching.

Or maybe get the wave cycle to reset at each switch, so every newly select wave has its cycle start at zero upon switching (if this wasn't the case already).

Thanks in advance :)

**Comment by mdemanett** [comment]
Good idea, will do.

**Comment by mdemanett** [comment]
I added an option to reset the phase.  I experimented with a fadeout but it didn't seem to work very well to me, I think it might be confusing.

Also, there is a "Smoothing" option now, already -- modest values like 10% might do what you want.

New option is in the new test release: https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test3

**Comment by Eurikon** [comment]
Thanks will check it out :)

**Comment by Eurikon** [comment]
I see up here in the comment that the reference is to LLFO, my request was for LVCO. 
Or do LLFO and LVCO share same code?

**Comment by Eurikon** [comment]
Yeah i just checked the LLFO module, you have added the request to the features of LLFO, which is nice btw! 

I think my question got somewhat lost in translation :) 

But i would love this option in LVCO, phase/wave reset upon clicking the little wave selector switch. 
To get rid of the little clicks.

![Screenshot 2021-09-23 at 19 06 43](https://user-images.githubusercontent.com/40998416/134552890-11f9e867-f5dc-4a3b-8f21-2ad6c673ff2d.png)

**Comment by mdemanett** [comment]
Yep, I totally read it as LLFO.  But anyway it makes sense in both.  New build with it in LVCO: https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test4

**Comment by Eurikon** [comment]
Superbbbb, you da man! Thanks a ton :D
