### ISSUE TITLE
8:1, and 1:8 Step CV

### ISSUE THREAD

**Issue by LollyWater** [bogaudio/BogaudioModules#183]
Hey, noticed that when CV'ing step selection, the total number of steps is ignored and all steps are cycled through. Cheers.

**Comment by mdemanett** [comment]
That's the intended behavior, but there is an unreleased option that makes it behave the way you want, probably. See #173 -- you can get a test build [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.37-test2) that has this.
