### ISSUE TITLE
Remove CC-NC clause for packaging

### ISSUE THREAD

**Issue by falkTX** [bogaudio/BogaudioModules#187]
Hi there.

I am interested on packaging your modules together with a special VCV build, for linux distributions.
The non-commercial clause on your artwork presents a problem though, due to linux ISOs being sellable in, for example, online stores and together in magazines.

This is a long shot but thought I would ask anyway, is there a possibility to the remove the non-commercial clause from your artwork so it can be packaged together with other tools/software?

**Comment by mdemanett** [comment]
Hey,

I'm leaning towards doing this.  To be clear, if I relax the graphics license to CC-SA, you'd be good to go?

**Comment by falkTX** [comment]
Yes, that is basically the same as GPL in code terms, just for artwork.
Anyone using your resources to build other things will need to share that artwork with the same license. Which seems fair to me.
Thanks for your consideration.

**Comment by mdemanett** [comment]
This is done.

Good luck with the project!

**Comment by falkTX** [comment]
Forgot to close the ticket since the issue is resolved.
Thanks again.
