### ISSUE TITLE
Mix 2 - add: Input 1 poly spread

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#188]
Hi Matt! 

could you please add this option:

![Screenshot 2021-12-01 at 13 35 18](https://user-images.githubusercontent.com/40998416/144235787-e5b64434-188c-4480-b597-3f22cb4812b3.png)

to the  "MIX 2" module 

![Screenshot 2021-12-01 at 13 34 20](https://user-images.githubusercontent.com/40998416/144236023-bffe2df8-d478-4fa5-a44a-fe1444aa8f63.png)

(but then ofcourse in pairs of 2).

? 😃 ?

cheers!

**Comment by mdemanett** [comment]
Hey, sorry I missed this, it's a good idea, will take a look.

**Comment by mdemanett** [comment]
Finally got around to making a test release that has this: https://github.com/bogaudio/BogaudioModules/releases/tag/v2.0.39-test2

**Comment by Eurikon** [comment]
Thanks! Will check it out asap!
