### ISSUE TITLE
PGMR v2 doesn't remember which column is selected when reloading patch

### ISSUE THREAD

**Issue by ContemporaryInsanity** [bogaudio/BogaudioModules#189]

**Comment by ContemporaryInsanity** [comment]
INV doesn't save state either.

**Comment by mdemanett** [comment]
For INV, for it to save state on reload, toggle on LATCH, and toggle on the "Save latched state to path" option in the right-click menu.

For PGMR, I would have thought that it does not remember the step.  Which is the case in v2.  In v1, it seems to restore to a random step, not necessarily the one selected on closing the patch.  This is weird, that something changed, will look into more, maybe can add an option to enable saving the selected step.
