### ISSUE TITLE
mix4/mix8

### ISSUE THREAD

**Issue by NRG70** [bogaudio/BogaudioModules#19]
Hi,
thanks for the wonderful modules.

Would be nice if the mixers had a small link button between each pair of the fader channels, that would link both faders to move at same time and value.

Also if the mutes had cv control and a mute on the master output with cv control as well.

thanks for your time.

**Comment by mdemanett** [comment]
Hi, thanks for the feedback.

I like the idea of the linked faders.  It might be a trick to pull off, though, given Rack's internal structure.  I'll look into it at some point.  Meantimes, of course, you can mult a single CV to the level input of multiple channels, and control them as a linked group that way.

I thought about CV for the mutes, but ran out of space and something had to go.  Again, you can patch it up via the level inputs.  If someone has a module like Fundamental Mutes, but with CV, that'd make it easy, but I don't know if that exists.

I'll think about a mute button for the master channel, I don't see why not.

**Comment by mdemanett** [comment]
New release has a master channel mute button on MIX4/8.  Also, MUTE8 has 8 CV-controlled mutes, can be patched in with MIX8.

**Comment by NRG70** [comment]
thanks! yeah i noticed the MUTE8 :D 
comes in handy! thanks again.
