### ISSUE TITLE
Bogaudio oscillators clicks and pops from PWM

### ISSUE THREAD

**Issue by tone-roche** [bogaudio/BogaudioModules#193]
All bogaudio oscillators with a pulse (VCO, LVCO, PULSE & XCO) produce audible clicks and pops when modulating the pulse width. The higher the frequency of the lfo or vco modulating the pulse width, the more frequent the pops and clicks become. This seems to be an issue with many but not all oscillators with pwm in VCV Rack.

**Comment by mdemanett** [comment]
Do you have sample patch?

**Comment by tone-roche** [comment]
Yes! Please see the patchstorage link. I'm unable to upload vcv patch files to github. Thanks for your help!!

https://patchstorage.com/bogaudio-pwm/

**Comment by mdemanett** [comment]
Oh, yeah, I hear it now.  Interesting.

**Comment by Petervos2018** [comment]
Maybe of interest : 

https://community.vcvrack.com/t/clicks-and-pops-from-pwm/15824/5?

**Comment by tone-roche** [comment]
@Petervos2018 Thanks for the solution!! Hopefully all devs can implement this.

**Comment by mdemanett** [comment]
I think this is fixed.  Fix is available as a [test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v2.0.39-test1) -- would be glad if some of you could test it!

It was basically the same problem as described on the forum link, with basically the same solution -- just don't update the effective pulse width more than once per oscillator cycle.

**Comment by tone-roche** [comment]
Testing now. Sounds great on all oscillators with PWM (VCO, PULSE & XCO). The issues seems to have been solved. Thanks for fixing this!
