### ISSUE TITLE
Additator Width, Osk, Esk params. are destructive: bug or feature?

### ISSUE THREAD

**Issue by jocphx** [bogaudio/BogaudioModules#194]
Hi,
I was curious about Additator, so I downloaded it, started to play with it and got stumped  within the first minute, after I moved any of the Width, O-skew, E-skew knobs, there is no way that I could get back to the oscillator original state. 

Double-clicking on each of those knobs seems to have more of a freeze effect than a "back to default value" one.

Any change applied to those 3 knobs will result in a change of their default values: hence the default wave is always different.

The only way I can get Additator to its original state is to click "Initialize" in the context menu or switch between "Sin" and "Cos" in the UI, sometimes. Some other times the wave is so "messed up" that also switching between Sin and Cos cannot re-init the plugin, only "Initialize".

I spent an insane amount of time trying to figure out how to use Additator, as a traditional oscillator, rather than as a "source of uncertainty" .

Am I missing something?

**Comment by mdemanett** [comment]
What happens is, after modifying one those then putting it back, the harmonic relative frequencies of the partials are restored, but they will have gone out of phase with each other -- the freeze effect comes from whatever out-of-phase situation is present when the frequencies are restored then being held.  Resetting the module (or doing the sin/cos thing, or sending a trigger to SYNC) restarts the partials, so they're then back in phase (but doing this causes an audible pop).

I hazily remember trying to deal with this back in the day, and giving up and deciding that's just how it will be.  Now you have me thinking about it again, there may be some way to add a phase-correcting mode or at least a non-popping soft sync or something.  No promises on that.

But anyway, short answer: it's a bug that has become a feature, or at least "character".
