### ISSUE TITLE
Bogaudio ADDR-SEQ causing module browser to crash

### ISSUE THREAD

**Issue by pgatt** [bogaudio/BogaudioModules#195]
Hi Matt,

User is pressing Enter in VCV to bring up the module browser and having the module browser on Mac crash. 
ADDR-SEQ seems to be at fault and the user has resolved their crash by removing BogAudio.

The log file is attached below.
[log.txt](https://github.com/bogaudio/BogaudioModules/files/7819377/log.txt)

**Comment by mdemanett** [comment]
Do you know the user's computer model and os version, by chance?  Is it particularly old (or new)?  The crash is "illegal instruction", usually meaning something about my code is being compiled in a way that user's system doesn't understand.  This is hard to fix.

If I made a test build with a (total guesswork, shot in the dark) possible fix, would the user be able to try it?

**Comment by pgatt** [comment]
VCV Rack Free 2.0.4, 
Mac 10.11.6 and I have asked the user their computer model.

I assume a test build would be appreciated, but I can check.

**Comment by mdemanett** [comment]
Find the test build on the page for [v2.0.39-test1](https://github.com/bogaudio/BogaudioModules/releases/tag/v2.0.39-test1), if you get a chance to try it.

A few things might happen:
 1. It may well fail in the same spot.
 2. It may fail in a different spot (there are a couple of other places that do something similar), but that would be good news as then I have a solution that just needs to be applied everywhere.
 3. It may work!  Maybe.

**Comment by pgatt** [comment]
Hi Matt, 

Sorry for the delay. I will send this through to the user and let you know how we get on. Thanks for the build and I understand it is just a test build to try and diagnose, and I will make that clear to the end user.

**Comment by pgatt** [comment]
You guessed it Matt, 2009 model. I have now sent to the user to test.

**Comment by pgatt** [comment]
User is reporting it's fixed. Thanks Matt! Will get back to you if it crops up again.

**Comment by mdemanett** [comment]
Cool, good news!  And yeah, let me know if there are further problems.
