### ISSUE TITLE
LLFO feature request

### ISSUE THREAD

**Issue by ContemporaryInsanity** [bogaudio/BogaudioModules#196]
I use LLFO a lot in conjunction with Stoermelder CV-MAP.
Please consider adding a context menu option to LLFO that will double (or more?) the offset available?  As is (+/-5V) I need an attenuverter between LLFO and CV-MAP to get the levels I want when LLFO scale is <100%, which is almost always.

Thanks as always for your great module collection.

**Comment by mdemanett** [comment]
This makes sense, I'll look into it.
