### ISSUE TITLE
Request - SWITCH81 - No Clip Mode

### ISSUE THREAD

**Issue by Nowhk** [bogaudio/BogaudioModules#199]
Hi master,

request: is it possible to add on SWITCH81 a "no clip" mode within the context menu?

![image](https://user-images.githubusercontent.com/19835752/155678706-727d3129-2a15-4930-bfbe-46bfd002523d.png)

I'd like to pass the signal "as-is" without any clip/saturation.

Thanks

**Comment by mdemanett** [comment]
Yeah I can do that.  Meanwhile, VCM has that mode (it's only four channels, though).

**Comment by DaveBenham** [comment]
I just came here to request the same thing. Thanks for taking this on.

**Comment by Nowhk** [comment]
Hi,

any news about this?

Thanks

**Comment by mdemanett** [comment]
Finally done; the change is available in this test release:  https://github.com/bogaudio/BogaudioModules/releases/tag/v2.0.39-test2

**Comment by Nowhk** [comment]
@mdemanett thanks. It seems working good. When this will be released officially?

**Comment by Nowhk** [comment]
Hi @mdemanett ,

tried this change request on 2.0.40, but seems it still limited to +-12V?

![image](https://user-images.githubusercontent.com/19835752/172114736-366c36bc-5ccb-4f7e-a675-dfe96b869bf2.png)
Here's I feed in a 10V * 2 (scale), and scope show +12V max, even with Output clip none.

Can you check it out?
Thanks

**Comment by Petervos2018** [comment]
There is a limiter in the offset module , turn that on/off to get the results you want : 

![afbeelding](https://user-images.githubusercontent.com/46076474/172152389-279a7465-2929-494c-8734-82be2ac2cd08.png)

**Comment by Nowhk** [comment]
Correct. Thanks!
