### ISSUE TITLE
Help Using Arpeggiator Module

### ISSUE THREAD

**Issue by InauspiciousIguana** [bogaudio/BogaudioModules#200]
I believe I'm sending in polyphonic pitches and gates, but I'm only getting one pitch from the output.  Thanks for any help you can give.

https://ibb.co/1d5cDdv
https://ibb.co/6sZj79X
https://ibb.co/QKWSrxV

**Comment by mdemanett** [comment]
It may work to toggle on "HOLD".  If not, see the notes under "To control ARP from modules other than MIDI-CV" [here](https://github.com/bogaudio/BogaudioModules#-arp).  If it still doesn't work, please post a copy of the patch here so I can try to figure it out.  Cheers.
