### ISSUE TITLE
Bogaudio modules going to a maximum of 12V not 10V

### ISSUE THREAD

**Issue by electron271** [bogaudio/BogaudioModules#201]

**Comment by mdemanett** [comment]
What's the question here?

**Comment by mdemanett** [comment]
OK, that's a bug.  The output should be limited to +/-12v.  It would also make sense to default the MIX knobs to something lower like 50%.

**Comment by mdemanett** [comment]
This was fixed in [v2.1.41](https://github.com/bogaudio/BogaudioModules/releases/tag/v2.1.41).
