### ISSUE TITLE
ugly stuff from valgrind, probably harmless

### ISSUE THREAD

**Issue by squinkylabs** [bogaudio/BogaudioModules#202]
I've been running some patches on Ubuntu using valgrind. don't ask....
Anyway, when I switch audio modules, this comes out:

==3098== Thread 12 RtAudio:
==3098== Conditional jump or move depends on uninitialised value(s)
==3098==    at 0x75380A8: bogaudio::dsp::SquareOscillator::setPulseWidth(float) (oscillator.cpp:163)
==3098==    by 0x73A8762: bogaudio::LLFO::modulate() (LLFO.cpp:106)
==3098==    by 0x743005C: bogaudio::BGModule::process(rack::engine::Module::ProcessArgs const&) (module.cpp:80)
==3098==    by 0x50215F9: rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&) (Module.cpp:345)
==3098==    by 0x501BCA8: Engine_stepWorker (Engine.cpp:323)
==3098==    by 0x501BCA8: Engine_stepFrame (Engine.cpp:395)
==3098==    by 0x501BCA8: rack::engine::Engine::stepBlock(int) (Engine.cpp:551)

**Comment by mdemanett** [comment]
Ha, I was missing a member variable initializer.  Thanks for catching it!

**Comment by squinkylabs** [comment]
happy to. btw, it is super, super easy to run valgrind. I run it on my win machine by running ubuntu inside a VMWare VM/
