### ISSUE TITLE
Matrix 44 doesn't produce unity gain

### ISSUE THREAD

**Issue by midiguru23** [bogaudio/BogaudioModules#203]
In developing a tutorial patch, I wanted to have available two or three pitch inputs to a single oscillator. To add an LFO for vibrato, for instance. So I used a Matrix 44 to combine the V/oct output from the MIDI-to-CV module with a signal from an LFO. What I've discovered is that when a Matrix 44 knob is set to 100%, it doesn't actually send unity gain of the input to the output. The signal is being attenuated slightly.

Here's how I can tell: If I route the MIDI-to-CV directly to an oscillator, I can play two notes on the keyboard that are several octaves apart (this is a polyphonic patch) and get perfectly in-tune octaves. But if I pass the V/oct signal through the Matrix 44 on its way to the oscillator, over a range of three octaves or more the two notes will not be in tune. The higher note will be flat with respect to the lower note, which indicates that the signal is being attenuated slightly.

If you're unable to duplicate this, let me know and I'll shoot a quick video demonstrating it. Thanks for developing such great modules, by the way. This is the first problem I've ever encountered in any of your devices.

**Comment by Petervos2018** [comment]
Could it be this setting ?

![afbeelding](https://user-images.githubusercontent.com/46076474/163711808-8a3456db-e712-4ace-99bc-8bdb08bcf5e7.png)

**Comment by midiguru23** [comment]
On 4/17/2022 4:08 AM, Peter Vos wrote:
> Could it be this setting ?

Yes, indeed. Thanks for pointing that out! Sorry about filing a useless 
report.

--JA
> 
> afbeelding 
> <https://user-images.githubusercontent.com/46076474/163711808-8a3456db-e712-4ace-99bc-8bdb08bcf5e7.png>
>
