### ISSUE TITLE
VCF cutoff changes when connecting FM input (with FM trim at 0)

### ISSUE THREAD

**Issue by jamshark70** [bogaudio/BogaudioModules#205]
Here's a very narrow band pass filter with center frequency = 100 Hz.

![bogaudio-vcf-disconnected-fm](https://user-images.githubusercontent.com/318301/171981236-14e24645-f2f6-4a60-bf50-02b599079d03.png)

Here's the same band pass filter, same center frequency set by the knob, but with an LFO connected to the FM input.

![bogaudio-vcf-connected-fm](https://user-images.githubusercontent.com/318301/171981305-9da2f3be-8787-41b4-b329-6de47a36e1a3.png)

Note that the FM trim knob is set to zero, which I interpret to mean that the FM input signal should have zero effect on the filter frequency.

But the frequency has changed, just by connecting the input.

I would have assumed that the frequency knob sets a baseline value, and 0V in the FM input (whether it's 0V, or trimmed down to 0) would deviate away from that baseline by exactly 0.

This kind of thing is tricky to fix because of backward compatibility -- an unknown number of patches in the wild depend on the current behavior. So it may be unfixable in VCF, but it might be nice to introduce another module.

"FM: an exponential FM input; the input here is attenuated by the FM knob, then added to the V/OCT input (which normals to 0V) before being converted to HZ."

Hm, but, exponential FM should map input 0 onto a frequency *ratio* of 1, i.e. `pow(some_value, volts)`, and then multiply Hz by this. That is, I guess that 0V is mapping to a positive value (which is necessary for an exponential function) but then being misapplied by addition.

**Comment by mdemanett** [comment]
Bug confirmed, will look into a fix.

**Comment by mdemanett** [comment]
This was fixed in [v2.1.41](https://github.com/bogaudio/BogaudioModules/releases/tag/v2.1.41).
