### ISSUE TITLE
VCA's output very low in Cardinal

### ISSUE THREAD

**Issue by the-wasters-of-time** [bogaudio/BogaudioModules#207]
Using both VCAMP and VELO, the output is very low, around -30 dB. I'm using CV from your DADSR(H)+. The same CV input into VCV VCA gives the expected output, around -6 dB. Using Cardinal VST3 version 22.06 on Linux.

**Comment by mdemanett** [comment]
This is just the difference between "linear" (linear in amplitude) and "exponential" (linear in decibels) VCA response.  VCAMP is exponential, and VELO and my VCA are by default (but have LIN toggles to make them linear).  Rack's VCA is linear by default, though you can switch to exponential on the context menu.  They'll all output the same level with a full 10V CV, at lower CVs exponential will be less.  But they all do the same thing when the modes match.

**Comment by the-wasters-of-time** [comment]
Oh yeah, that works, thanks. My apologies.
