### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by NRG70** [bogaudio/BogaudioModules#21]
Hi Matt, 
i have a personal dark theme 80% Gray that i use for your modules.
Several members approached me for this svg mod.
I can not share this with them since that is not the right thing to do.
If you like it and are interested you could include it with your modules as an alternative to your light theme.
Let me know. 
Take care!
![bogaudio-darkgray80](https://user-images.githubusercontent.com/40998416/46258310-a07f4a00-c4c8-11e8-8ae7-21562c255e16.jpg)

**Comment by mdemanett** [comment]
Those look pretty cool.  

I'm not too interested in doing the work to maintain a dark theme, at least not right now....

But, there's no reason you can't share these around, in fact I encourage you to.  All the code, including the SVG code, is open-source, and anyone can do what they like with it.  Modifying the visuals to your taste, and sharing that work with whoever likes it, is entirely in the spirit of things.  

Ideally, you'd share the work here on github (e.g. fork this repo, and publish the changes on the fork), but there's no requirement.

**Comment by NRG70** [comment]
ah ok! thanks that is good to know that i can share it.
they'll just have to maintain it themselves then. 

thanks for clearing that up:)

**Comment by NRG70** [comment]
forked:
https://github.com/NRG70/BogaudioModules

please let me know if anything there should be removed or edited.

**Comment by mdemanett** [comment]
Looks good!
