### ISSUE TITLE
Add Output Clipping options to SWITCH18 and MATRIX18

### ISSUE THREAD

**Issue by DaveBenham** [bogaudio/BogaudioModules#210]
SWITCH18 and MATRIX18 always employ soft clipping, so it is impossible to pass CV through without some level of distortion.

All the other SWITCHnn and MATRIXnn modules have Output Clipping options in the context menu that allow disabling clipping or usage of hard clipping. Please add those options to SWITCH18 and MATRIX18.

I prefer a default of no clipping, or else hard clipping at 12V for all the SWITCHnn and MATRIXnn modules, as I typically use them for CV. And when I do use them for audio it is rare that the output would exceed 12V, so I would prefer straight passthrough.

But I suppose it is too late to change the defaults without breaking existing patches. Or possibly I am in the minority.

Any way, thanks for your modules - It is rare that I create a patch without using your plugin.

**Comment by mdemanett** [comment]
I can add that.
