### ISSUE TITLE
POLYMULT CHAN input does not seem to function

### ISSUE THREAD

**Issue by strangebuttrue** [bogaudio/BogaudioModules#215]
I put some voltage in this port and nothing seemed to happen - too bad, because this is a pretty handy function! I'm running Rack 2.2.0 on Windows.

![CHAN PROB](https://user-images.githubusercontent.com/76659301/204034067-e9a7118d-7224-4250-8b7b-77a89be0b07d.jpg)

Other than this: Thanks for the excellent modules!

**Comment by Petervos2018** [comment]
Don't connect the channel with the 10V.

![afbeelding](https://user-images.githubusercontent.com/46076474/204035946-e9a7e1ff-3de9-47c0-8dcd-2ab5a94fb32c.png)

**Comment by mdemanett** [comment]
The first behavior was as designed -- CHAN wasn't a real CV input, it would just take the poly channel count from whatever is patched there.  But, if the input is mono it may as well act as a CV, so I added that (0-10V, where 10V will give the max channels as set by the knob).

For the second thing, with two POLYMULTs, it was using the poly sum of the input as a value to copy to the outputs.  I changed it to use the first channel.

I forgot to tag it, but the changes are in commit [af89861](https://github.com/bogaudio/BogaudioModules/commit/af8986180c0c4847c0039bd666099ffbd12b57d2).

**Comment by Petervos2018** [comment]
Hi Matt,

Thanks for answering and the planned changes, don't know if this answers @strangebuttrue question but it does mine.

Greetings Peter.

**Comment by mdemanett** [comment]
Hey Peter, thanks as always for jumping on this and figuring it out!

**Comment by strangebuttrue** [comment]
Most excellent @mdemanett , thank you! I will keep an eye open for the next update

**Comment by mdemanett** [comment]
Took a while, but this is finally released to the library.

**Comment by strangebuttrue** [comment]
NICE, THANK YOU
