### ISSUE TITLE
Question about phase inputs on 4FO, 8FO

### ISSUE THREAD

**Issue by grough** [bogaudio/BogaudioModules#218]
Hi there - Both 4FO and 8FO have one "PHS" input per oscillator. When I connect a cable to one of these inputs and change the voltage, I don't see a phase shift on the output. Have I misunderstood the purpose of the PHS inputs? I'm running Bogaudio 2.1.41. Thanks for your excellent modules.

**Comment by Petervos2018** [comment]
In order for this to work you need to "open" the phase they are now attenuators.

![afbeelding](https://user-images.githubusercontent.com/46076474/208323917-05883729-a4f4-4d69-9caa-4ce7a320895c.png)
