### ISSUE TITLE
SLEW does not work properly in slow mode with sample rate above 48 kHz

### ISSUE THREAD

**Issue by DaveBenham** [bogaudio/BogaudioModules#221]
As long as VCV sample rate is 48 kHz or below, then SLEW in slow mode seems to work just fine.

Bat at 96 kHz and SLEW in slow mode, rise / fall at 10 (100 s/V), and current voltage at 0 or 10 V, then a 10 volt change results in no change. For example, when applying a toggled 10V gate to the input.

With a VCV sample rate of 196 kHz and SLEW in slow mode, the output never moves, regardless what the input value is or the Rise / Fall setting.

Tested on both Windows and Mac. My VCV version is 2.1.2

**Comment by mdemanett** [comment]
Interesting.  I'll take a look.

**Comment by mdemanett** [comment]
Should be fixed; at high sample rates some the numbers get very small, and it would stop updating.

**Comment by DaveBenham** [comment]
Great news. Thanks :)
