### ISSUE TITLE
S&H: Not normalized to noise

### ISSUE THREAD

**Issue by ZwergNaseXXL** [bogaudio/BogaudioModules#224]
I'm afraid issue #18 is back in version 2.1.41.

**Comment by Petervos2018** [comment]
Are you sure ?

![afbeelding](https://user-images.githubusercontent.com/46076474/224547901-6b6254a9-ae6d-4293-b30d-7dbdd3c10e2f.png)

**Comment by ZwergNaseXXL** [comment]
It didn't work in my patch, even when I duplicated the S&H module and re-initialized it. Now I added a fresh module and it worked. Turns out it's the polyphony setting in the context menu. From GATE input -> works. From IN input -> doesn't work. I'm not even using polyphony, but I think the normalization should work regardless of polyphony or the setting.

**Comment by mdemanett** [comment]
There was a bug in the poly channels calculation.  Thanks for noticing!
