### ISSUE TITLE
ADDR-SEQ and ASX Bug

### ISSUE THREAD

**Issue by knchaffin** [bogaudio/BogaudioModules#228]
I am running VCV Rack Pro latest release 2.3.0 under Windows 11.

Several of us in the VCV community have experienced an issue with patches that use 1 ADDR-SEQ with 7 ASX instances (or perhaps with additional ADDR-SEQ and ASX modules).  This seems to happen upon Rack launch or patch load and manifests itself when it occurs as the ADDR-SEQ STEPS knob indicating less than 64 steps, usually 16.  When this happens to me, I seem to be able to load another patch in the same Rack session and then re-load the problem patch and the steps will often be correct, but sometimes not.  This makes me think the problem is more likely linked to patch load and initialization than to Rack launch, but a Rack launch re-loads the last autosaved patch, so I see the problem upon Rack launch with a problematic patch quite often.

To see the problem, hover over the first ADDR-SEQ STEPS knob and when the problem occurs, the STEPS will indicate less than 64, usually 16.  I discovered this bug by listening to the chord progression patch and hearing the mess-up, but that is tedious.

Sometimes the bug goes away for a few hours, which is weird. 

Here is a zipped .vcv patch file that exhibits the problem, usually in the top ADDR-SEQ and ASX block.

[Multiple Sequential Switches switching Full Hotel Fun Song-2.zip](https://github.com/bogaudio/BogaudioModules/files/11990613/Multiple.Sequential.Switches.switching.Full.Hotel.Fun.Song-2.zip)

Here is a bare-bones patch that exhibits the problem for me.

[Multiple Sequential Switches switching Full Hotel Fun Song bare-bones -2.zip](https://github.com/bogaudio/BogaudioModules/files/11990669/Multiple.Sequential.Switches.switching.Full.Hotel.Fun.Song.bare-bones.-2.zip)

**Comment by DaveBenham** [comment]
Once the bug manifests, it is easily fixed by temporarily moving the 2nd expander away from the 1st, breaking the chain, and then restoring it to the correct chained position.

**Comment by mdemanett** [comment]
Fixed in release 2.4.44, out on the VCV library.
