### ISSUE TITLE
ARP crashing patches

### ISSUE THREAD

**Issue by Cubistguitar** [bogaudio/BogaudioModules#229]
Not sure the issue, I am mostly a newb, but over and over ARP has crashed my current patching.

I have included a log text from a recent crash. 
Thanks immensely for the terrific modules and the continued support of those same modules.

[broke bogARP log.txt](https://github.com/bogaudio/BogaudioModules/files/12061858/broke.bogARP.log.txt)

**Comment by mdemanett** [comment]
Fixed in release 2.4.44, out on the VCV library.
