### ISSUE TITLE
VCA lacks Amplifier/VCA tag

### ISSUE THREAD

**Issue by darloth** [bogaudio/BogaudioModules#23]
I realize this -might- be intentional, since it's a VCAttenuator rather than strictly speaking an amplifier...

But, nevertheless, many other things that only attenuate (like the VCA-1 from Fundamental, and many other VCAs) also behave that way, and all of those are in that tag.

As such, I expected the 3hp VCA to have that tag, so I have made an issue in case it's unintentional.

**Comment by mdemanett** [comment]
Yeah, I did that on purpose.  I have the VCAMP on the amplifier tag, since it's actually an amplifier.
