### ISSUE TITLE
Re-use some of your DSP in Surge family projects

### ISSUE THREAD

**Issue by baconpaul** [bogaudio/BogaudioModules#238]
Hi!

First, thanks for writing awesome rack modules. I think every patch I write has Surge XT and Bog in it :)

I'm planning on re-coding but borrowing some of your DSP for surge projects (the non-rack ones), especially envelope follower and pressor are very useful guides. Because of the way surge architecture works I'd end up re-coding the DSP, and we are all license compatible, but I'd definitely plan on giving you the appropriate credit in headers, documentation etc...

While I could do this without asking, I always think it's kinda rude to not ask (or at least notify!) first, so just want to check how you'd like to be credited, and if you have any objections beyond the license you'd like me to consider.

Best,

**Comment by mdemanett** [comment]
Hey, go for it, I have no issue with that.

You're welcome to put a "[XYZ feature] based on https://github.com/bogaudio/BogaudioModules" in your README acknowledgements or whatever, but not necessary at all.
