### ISSUE TITLE
Feature Request: Unipolar/Bipolar Switch on LFOs

### ISSUE THREAD

**Issue by lnikj** [bogaudio/BogaudioModules#24]
Hi

Any chance of implementing a Uni/Bi switch (0-10/-5+5) on the LFOs?

Thanks.

**Comment by mdemanett** [comment]
The offset and scale knobs let you dial in whatever range you like.  The defaults get +/-5.  Turn offset all the way clockwise for 0-10.

**Comment by lnikj** [comment]
Oops. Sorry. Thanks!
