### ISSUE TITLE
Love the modules, would like to see some filters

### ISSUE THREAD

**Issue by Shadowhenge** [bogaudio/BogaudioModules#26]
I wanted to challenge myself and create a "default" rack with all Bogaudio modules as a platform to build on and realized you have no filters.  Are there plans to "round out" your module collection by adding the commonly needed modules?  Also would like to see a brand logo blank plate I can show off when I do a Youtube video using one or more of your modules.  I have some design ideas for the graphics and operation if you are interested.  (Have a few module ideas but I'm a designer, not a programmer.)  Wouldn't mind donating some time if needed.

**Comment by Shadowhenge** [comment]
![filter concept](https://user-images.githubusercontent.com/44178070/47122304-7d2bfd00-d233-11e8-90ef-e93c73aaabd7.jpg)

This is kind of what I had in mind.

The top Selector is the filter model
HP - High Pass 
BP - Band Pass
LP - Low Pass
SV - State Variable
RC - Resonant Comb
DL - Diode Ladder
SP - Steiner-Parker
BS - Bent State

Would rather the HP, BP, and LP be an individual 3-way selector in retrospect.

The Bottom Selector for the Noise Generator is to add an adjustable level of noise to the signal, pre-filter, in order to add complexity for the filter to chew on.
W - White Noise
P - Pink Noise
B - Blue Noise
R - Red Noise
INV - Inverse of incoming signal

There are CV ins and attenuverters for all variable functions

Dual Out is a cloned output so a filtered output can be split to multiple upstream processors independently without a separate splitter, though I think perhaps the outputs should have a standard and perhaps thru.

the +db inputs are for various levels of input pre-gain.

Attack and Decay functions are for how long after a signal is input before the filter effect glides to a change in frequency CV, and glides from a change.  You could think of it as a dual glide feature to provide an envelope to filter changes.  Alternately it can be used in conjunction with the dual outputs to have the filter effect faded into and out of an otherwise clean signal without having to automate a separate set of controls.

**Comment by mdemanett** [comment]
Glad you like the modules.  Eventually I'll have a complete system...current roadmap is something like:
  - Sequencers, clocks, etc
  - Filters
  - Effects
And random things along the way.  But it'll take time, maybe a long time.

Your mock has come cool ideas.  Again, maybe someday.

**Comment by mdemanett** [comment]
Bogaudio has filters, now.
