### ISSUE TITLE
CV not Affecting Dry/Wet Mix on CVD-CV Delay

### ISSUE THREAD

**Issue by jonheal** [bogaudio/BogaudioModules#27]
I have an external controller encoder mapped to the CV jack beneath the Dry/Wet mix knob on the CVD, but the encoder does not seem to change the dry/wet mix. I can see voltage is being applied because the jack lights up. Maybe this is not the intended purpose of this jack?

**Comment by jonheal** [comment]
I think I see my error now. Your manual states the Dry/Wet knob needs -5/5 volts and I am applying 0/10 volts. I need to figure out how to offset 0/10 volts down 5 volts.

**Comment by mdemanett** [comment]
You're right on both counts...it expects a +/-5 signal, but it's also broken.  Fix will go out in the next release, maybe next week.  Thanks for the catch!

**Comment by jonheal** [comment]
Thanks much!

--
Jon Heal
http://www.theheals.org/
Have a nice day!

**Comment by mdemanett** [comment]
Oof -- I forgot to check the range on the parameter when the CV is in use.  It can go out of range and cause the crash.  Will release a fix soon.

Thanks for the report, and for sticking with the module.

**Comment by jonheal** [comment]
I really like your modules. They are the best of the third-party modules, in my opinion.

--
Jon Heal
http://www.theheals.org/
Have a nice day!

**Comment by jonheal** [comment]
You’re the man. 😶

--
Jon Heal
IT Specialist, Information Services Division - Business Solutions Management Branch
United States Department of Agriculture | Foreign Agricultural Service | Office of the Chief Operating Officer
202-720-5728 (Desk)
202-256-9637 (Cell)
Have a nice day!
