### ISSUE TITLE
Mac 0.5.0

### ISSUE THREAD

**Issue by charlescrammond** [bogaudio/BogaudioModules#3]
[BogaudioModules.Mac.0.5.0.zip](https://github.com/bogaudio/BogaudioModules/files/1495268/BogaudioModules.Mac.0.5.0.zip)

Love these amazing modules! Folk asking for a Mac build on the FB group so I'm uploading a build here.

**Comment by mdemanett** [comment]
Thanks!

The full set for 0.5.0 is on the releases page now: https://github.com/bogaudio/BogaudioModules/releases
