### ISSUE TITLE
0.6.12 update nissing dark panels (res_b folder)

### ISSUE THREAD

**Issue by fractalgee** [bogaudio/BogaudioModules#31]
Looks like the latest update to 0.6.12 forgot to include the res_b (dark panel) folder, so stuck with only light panels until fixed... Not as nice on the eyes (MacOS X, Rack 0.6.2c)

**Comment by mdemanett** [comment]
I don't maintain the dark panels -- get them over here: https://github.com/NRG70/BogaudioModules
