### ISSUE TITLE
MUTE8

### ISSUE THREAD

**Issue by NRG70** [bogaudio/BogaudioModules#34]
Hi there,

when using this module with core midi-cc attached to the mute triggers, it reacts instantly when muting, but when un-muting it takes nearly a second to un-mute.

hope i am saying this right?
i am triggering from a beatstep-pro. tried both options for the buttons on the beatstep (toggle/gate), both have same behaviour, on release of the button it takes nearly a second for the MUTE8 to un-mute.

**Comment by mdemanett** [comment]
I replicated it...looks like for whatever reason, the output from MIDI-CC doesn't go to zero for that extra time (it goes close but not exactly zero).  MUTE8 uses Rack's standard trigger which looks for the signal to go to zero.

I should be able to fix it, but it might take a minute.

Here's a workaround: take the signal from MIDI-CC through OFFSET to MUTE8, then set the offset knob to slightly negative.  Thus the signal goes below zero when the CC is off and everything works as it should.

**Comment by NRG70** [comment]
ok, thanks, i read the thread.
then if it is a known issue that is living within the rack standards, i take it there will be no change on VCV rack's side, and the situation regarding Mute8 can only be solved through your proposed work around?

**Comment by mdemanett** [comment]
Sounds like I should change the triggers in MUTE8 (and everything else) to use 0.1V as the off voltage -- since that's actually the standard even though it doesn't happen by default.

Which I'll do, but I can't say when it'll be done and released.  The workaround is your friend in the meantime!

**Comment by NRG70** [comment]
ok, thanks, Matt! ;)
