### ISSUE TITLE
Analyzer and Analyzer-XL 0.6.13

### ISSUE THREAD

**Issue by therealkitman** [bogaudio/BogaudioModules#35]
Hi, I was just fooling around with harmonics from various VCOs and observing via the two analyzers. I noticed that the fundamental frequencies displayed at the top of each trace was slightly out. For example injecting a A4 440Hz signal always displays as 444Hz. I added a Calf Analyzer via an audio output and got a better result. See pic.
![image](https://user-images.githubusercontent.com/14888092/51881441-1d0e3080-23b6-11e9-89a0-37bea6e12ea0.png)

It's not a fatal thing but wonder if there is a calibration issue in the two analyzers.

Regards.

**Comment by mdemanett** [comment]
Hey...with this implementation, it's not going to report exact frequencies.  It uses an FFT, which outputs N frequency bins, where each some fixed width in HZ.  The width varies with sample rate and quality setting, but the finest is around 10hz (the current value is displayed on the top left).  For exact frequency detection, use something like NYSTHI Hot Tuna.

That said...it looks like the center frequencies of the bins are being calculated incorrectly.  I'll look into that.  Thanks for catching it!

**Comment by mdemanett** [comment]
Fix released (finally).
