### ISSUE TITLE
Mix4/Mix8 No Panning?

### ISSUE THREAD

**Issue by therealkitman** [bogaudio/BogaudioModules#36]
Hi, I have found that the CV inputs for the PAN function do nothing if the PAN knob is centred. CV input will only effect audio if the PAN knob is either hard left or hard right. For version 0.6.13 of both.

Regards.

**Comment by mdemanett** [comment]
That's by design; when something's connected to the CV input, the knob acts as an attenuverter -- the signal is scaled by the setting of the knob, positive or negative.  At center it zeroes out the CV.
