### ISSUE TITLE
mix 4 / mix 8

### ISSUE THREAD

**Issue by NRG70** [bogaudio/BogaudioModules#38]
hi, 
could you please add this functionality:

Right click on mixer channels mute button for SOLO channel,
with visual confirmation of this action ie: change mute button color.

Thanks.

**Comment by mdemanett** [comment]
It's a good idea, I'll look into it.

**Comment by NRG70** [comment]
Thanks Matt!

**Comment by mdemanett** [comment]
This is released, finally.
