### ISSUE TITLE
 All LFOs: Slow Mode switch

### ISSUE THREAD

**Issue by patman023** [bogaudio/BogaudioModules#40]
[Rack standard](https://vcvrack.com/manual/VoltageStandards.html#pitch-and-frequencies) is that LFOs should be 0V=2 Hz / 120 BPM, or a touch off C<sub>-3</sub>.

"Normal" mode = 16.35 Hz (C<sub>0</sub>)
"Slow" mode = 1.02 Hz (C<sub>-4</sub>)

Is there any chance you could add a toggle in the context menu for Slow = 2 Hz? It'd be nice to have your LFOs behave as expected when swapping for another, especially given their mechaSquirrel (mS) efficiency!

**Comment by mdemanett** [comment]
I did LFOs before there was a standard, or before I was aware of it, and so far haven't gotten around to complying for fear of breaking patches.  But the context menu could be a solution, or maybe it's just time...will look into it.

**Comment by mdemanett** [comment]
This is fixed (and released).  New instances of an LFO (etc) get the new behavior -- ones in existing patches will keep the old.  A context-menu item allows switching the behavior in either case.
