### ISSUE TITLE
BUG: UMIX not adding precisely

### ISSUE THREAD

**Issue by patman023** [bogaudio/BogaudioModules#42]
![image](https://user-images.githubusercontent.com/36520477/55764444-c1e96180-5a28-11e9-9787-99982625c4e4.png)

**Comment by mdemanett** [comment]
Indeed, there's a saturation effect applied, that soft-limits the mix at a bit less than +/-11V.  This meant to be an analog-ish effect and works well for audio.  I suppose I could add a CV mode where the sum is precise with a hard clip at +/-12V.  

SUMS is a precise adder, though only 2 inputs.

**Comment by patman023** [comment]
Is it meant to soft-clip through the entire range?

**Comment by mdemanett** [comment]
The way it's implemented, it does slightly, yes.

**Comment by mdemanett** [comment]
Reopened -- going to implement the precision adding mode as "CV mode" on the context menu.
