### ISSUE TITLE
BUG: CMP's A>B output not behaving per label

### ISSUE THREAD

**Issue by patman023** [bogaudio/BogaudioModules#43]
CMP's A>B output is acting like an A [Less than or equal to] B, and going high when the EQUAL output is active.

[bogbug.vcv.txt](https://github.com/bogaudio/BogaudioModules/files/3056688/bogbug.vcv.txt)

**Comment by patman023** [comment]
I see this is operating as per documentation, but I would suggest changing the output label, as it's highly unintuitive.

**Comment by mdemanett** [comment]
Good catch, thanks.
