### ISSUE TITLE
mix 1 , module request

### ISSUE THREAD

**Issue by NRG70** [bogaudio/BogaudioModules#44]
Would you please consider if feasible for you, to create a 3hp 1 channel mix/vca fader module,
the direct out is starting to come indispensable within an existing signal path.
And as the current mixer modules are cramped / not offering space anymore for "post fader direct out", such a tiny module would come in handy.

![bogaudio-mix-1](https://user-images.githubusercontent.com/40998416/55799781-7f7c5f00-5ad2-11e9-8b0c-600d6152f3e8.jpg)

**Comment by mdemanett** [comment]
I like the idea.  VCAMP is already mostly this (but no mute).

**Comment by NRG70** [comment]
AH yes, in my hurry to share my thought with you i didn't even look first in the existing modules!
VCAMP is that exactly, if it could get the mute button with cv, would be even more awesome!

**Comment by mdemanett** [comment]
MIX1 added.
