### ISSUE TITLE
Is there a branch that will build for VCV 1.0?

### ISSUE THREAD

**Issue by squinkylabs** [bogaudio/BogaudioModules#45]
It's difficult working on plugins without your analyzer available.

**Comment by mdemanett** [comment]
Not yet.  I built Rack v1 the other day, but haven't gotten any farther.

**Comment by squinkylabs** [comment]
I back-ported one from V1 to V0.6 so I would use analyzer XL on it. Well worth the effort ;-)

**Comment by mdemanett** [comment]
There's a branch v1 up now.  Needs more testing and TLC but basically works.
