### ISSUE TITLE
Feature request for the sequencers

### ISSUE THREAD

**Issue by MaZe6K** [bogaudio/BogaudioModules#46]
Hello there!
First of all thank you for these great modules! Especially for the FM-OP, which is just wonderful!
The sequencers are also really nice, but I was wondering if you might want to add a shift function to the sequencers.
What I mean is a control next to the step length that shifts the starting point of the sequence (offsets the sequence), and then it would also be nice to be able to automate sequence length, offset and toggle between forwards and backwards with a gate. With these functions I would consider them perfect.

**Comment by MaZe6K** [comment]
Wait a second... I just realised that you can already do this with the selector... wow, that's great!

Then maybe just a gate input to toggle between forwards and backwards and a voltage input for the length? :)
These are not that important to me since I will hopefully soon be able to automate them with MIDI, but would add functionality for crazy sequencing.

**Comment by MaZe6K** [comment]
... and maybe you could add a right-click-menu-option to wait for the next gate before the Selector jumps to that step? What I like to do is have a short sequence and play with it by shifting it around, but if I'm not in sync with the gate it can get a bit glitchy...

**Comment by MaZe6K** [comment]
Actually, one more thing... :) 
It would be nice if the step length would go all the way down to one step, so that the sequencer just puts out one value constantly when the length is 1.

**Comment by mdemanett** [comment]
Hi, glad you like the modules!

I like these ideas...I'll look into the 1-step and S&Hing the Selector.  CV for steps and direction would be cool, but there's no room for the input ports on the panels, and I don't want to make the panels bigger.  Hopefully the midi mapping will work for that.

**Comment by MaZe6K** [comment]
That's great!
I'm really looking forward to playing these things with a MIDI controller when 1.0 comes!

**Comment by MaZe6K** [comment]
Very cool! Thanks!
But right now they crash Rack when I try to load them... I currently use the Rconian (I think that was the name...) build on windows 7, so maybe it doesn't happen with the official build.

**Comment by mdemanett** [comment]
They're working again.
