### ISSUE TITLE
Dark mode for the GUIs ?

### ISSUE THREAD

**Issue by smok-e** [bogaudio/BogaudioModules#47]
First I want to thank you for your great modules, I use them in every project I do in VCV.
my question:
Would it be possible that you add a dark mode to the interface of your fantastic modules? (Like the Geodesics e.g.)
I did a dark version for the mixers, which I use only on my private pc,
and I like this very much. (see the attached picture)
 
I also know there are some visually impaired users, which have problems with the light versions. 
These would benefit from the dark GUIs.

I understand, that changing the GUI is a lot of work, but I think if you post a request in the VCV forum for some help,
there will be some folks that would support you ;-)
![Bogaudio_dark_1](https://user-images.githubusercontent.com/25061474/57191790-a4c18900-6f29-11e9-8dbc-af5e2d29f680.jpg)

 I can send you the svg's, if you want them.

**Comment by mdemanett** [comment]
Hey, glad you like the modules.

Check out this older issue:
https://github.com/bogaudio/BogaudioModules/issues/21

I still don't really have the bandwidth to maintain a dark mode, but as on that issue you can find one here: https://github.com/NRG70/BogaudioModules

It looks to be a few new modules out of date.  Nothing stopping you from updating it, or making a new one, or getting a community project together to do it.

**Comment by NRG70** [comment]
Hi Matt and Stephan,
yes the repo in my account is a few modules out of date.
I haven't had time yet to update it. 
But i also don't know how to sync it, so that your most recent version with the newest modules is automatically in my account.
I thought that would happen automagically,

**Comment by mdemanett** [comment]
Github doesn't automagically pull in the changes...instead you merge my upstream changes into your fork, and the push up the merged code.  Here are their instructions:
https://help.github.com/en/articles/syncing-a-fork
I guess there's no way to do it from the website.  It's all very cryptic, but should work.

**Comment by NRG70** [comment]
am i to understand that i need to use some software here on my computer, to maintain a fork?
and then i am able to sync it, and upload it to my git.
That is a lot of workaround for just editting and maintaining some svg files hehe :) 

i need to think of a more easier method for all this. 
thanks for helping out Matt! 👍

**Comment by smok-e** [comment]
@NRG70 I would like to have a dark version fork with already compiled modules.
Or only the dark svgs. I think that compiling is for many users too complicated and not possible.
So if you're up for that, we can use your fork.

**Comment by NRG70** [comment]
@smok-e I haven't compiled or build anything. I simply forked from a certain older version from Matt. And edited the svg files.
You can take the svg files from here, and get the missing svg files from Bogaudio current version. 
To continue from there?

**Comment by NRG70** [comment]
This is where you can find my edit:
https://github.com/NRG70/BogaudioModules

**Comment by Eurikon** [comment]
these have been updated to V1:
https://github.com/Eurikon/Bogaudio_Darktheme

**Comment by Eurikon** [comment]
@mdemanett 
Hi Matt, i have updated all dark svg to reflect the upcoming update which includes the new modules from issue #80 and the new little vco's.

I was wondering for the next release of your plugin, would it be possible for you to add my dark theme to your styles.hpp so that it can be a switchable choice in the context menu.
This is now found in many plugins and works very well instead of double svg's, doesn't need any other space in your repo either.

Cheers,
Latif

**Comment by mdemanett** [comment]
Hey Latif, sounds good, though there are more modules coming still...I'll ping you when the release is up.

Looks like maybe official dark mode support will come with rack v2...I'll probably wait and see how that goes and make dark mode part of the plugin then.

How do you generate the dark panels anyway?  Is it just a color invert?

**Comment by Eurikon** [comment]
No, i edit all the elements that you designed, and change their color manually. 
But it would be much easier if it was done through the styles.hpp

One of the contributors at the forum made the dark style for Surge plugin for example by editing the style.
And Paul added the other color schemes to the styles file as well, so that it can be switched on the fly. 

Good thinking to wait and see which method Andrew will use for the dark mode. 
Thanks for considering :)

**Comment by Eurikon** [comment]
Hi Matt, 
so the latest news on V2 as i read in some posts here and there.
It seems that the update is still a long way off from now and possibly planed for early next year.

Could it be possible for you to reconsider making dark theme part of the already existing Bogaudio plugin, 
in same way as some other plugins are doing it (Surge Rack / Submarine) through the styles.hpp file?

I can ask a forum user who has helped out with the Surge Rack theming, to see if he wants to help out?

**Comment by mdemanett** [comment]
Hey Latif, it is actually finally on my radar to do this soon, at least to get a central stylesheet you all can edit.  But probably also with an official dark mode.

**Comment by mdemanett** [comment]
DARK MODE is finally here!  Or at least ready to test.  Installable test builds are [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.33-test1).

There are actually two new skins; "Dark" is more classic:
![dark](https://user-images.githubusercontent.com/49971/89616767-f35d8180-d856-11ea-8bd5-e2967122bb59.png)

"Dark (low-contrast)" is less stark; @Eurikon this is basically your design, or at least that's what I was going for:
![lowcontrast](https://user-images.githubusercontent.com/49971/89616750-eb9ddd00-d856-11ea-81a0-e18d27067a78.png)

Each module has a "Skin" context menu, which setting overrides the default.  The default is "Light", which should look mostly like it always has.  

You can set the default skin: create a file named `BogaudioModules.json` in your `Documents/Rack` directory.  Make the contents be exactly this:
```
{
    "skins": {
        "default": "dark"
    }
}
```
You can change "dark" to "lowcontrast" as well.

Feedback is welcome.

(I already noticed, taking these screenshots, that the screws are positioned over the module name on some modules; will fix.)

**Comment by smok-e** [comment]
Hi Matt,

I had a little testdrive with the new dark modes,
here on Win10 everything seems to work as expected.
I tried the json file for the default setting, and it works fine.

well done !!!

**Comment by Eurikon** [comment]
Matt!! Thank you so much for making this happen :D 

Editing the json file works like a treat, and also makes the thumbnails in the browser show up in the chosen color, love it!
Great job, love the low-contrast style :) 

Might need some inspection, i will let you know if i find anything. 
The first being: S&H module: TRK & INV text needs editing.

Thanks again for making this part of your plugin, well done!

**Comment by mdemanett** [comment]
Here's an updated release: [v1.1.33-test2](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.33-test2)

I fixed the S&H labels (good catch, thanks!!) and screw positions.

Also, you'll need to rename `BogaudioModules.json` to 'Bogaudio.json'.  Now the filename matches the plugin slug.

I'll probably let this sit a couple days, to see what other problems turn up, and then release next week.

**Comment by smok-e** [comment]
the updated version is fine here,
the Bogaudio.json works too.

Is there any chance that the "default json" (Bogaudio.json) file can be created via the right click menue, as the plugins from Count Modula and Geodesics do?
I'm just asking, because I think that would be easier for many users.  But it's not a big problem imho.

**Comment by Eurikon** [comment]
I was also wondering why this was not the case, as also Submarine and Impromptu has this like that.

**Comment by Eurikon** [comment]
I took a close look at all module sin low-contrast theme, all looks fine to me.
Even the top left screw in Switch 1616 has been integrated smoothly in the plate design!

on a side note,
i did not know there was a MIX 2 , very useful!

and can you describe a use case / purpose for : Assign ?

**Comment by mdemanett** [comment]
Another DARK MODE build [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.33-test3)...as suggested I added menu items to set the default.  Modules using the default skin should update immediately.  Sometimes the module browser won't update, because it has its own caching...if you scroll far enough, then back, it will update.

Thank you guys for the testing and feedback!!

**Comment by Eurikon** [comment]
Is it necessary to allow theming on a per module basis?
I have not seen this in other plugins, and maybe it is a bit too much?

If you would simplify it to 3 choices for the whole plugin: light / dark /lowcontrast
And then the one chosen is the default, that seems a bit more structured and a less confizzled menu :)  

But of course that is just my opinion.

**Comment by Petervos2018** [comment]
> 
> Is it necessary to allow theming on a per module basis?
> I have not seen this in other plugins, and maybe it is a bit too much?
> 
Lindenberg does this so does Impromtu and Geodesics

And to be honest I like to have that option.

**Comment by Eurikon** [comment]
Ah ok, wasn’t aware those other plugins do that!

**Comment by n0jo** [comment]
The dark modes are fabulous, Matt. I like the low contrast in particular. Here is a couple of notes I made when checking it out:

- SOME MODULES: slightly different green values on status lights (e.g. LVCO or LLFO)
- PGMRX: select lights stay off
- PEQ14: frequency modulation range switch light stays on 0CTV regardless of state
- LVCF: mode lights stay off

Would you by any chance consider an additional dark/low contrast mode where the background of the ports is darkish too? It's very clear and usable right now, at the same time it looks a bit like leftovers from the light mode, if you know what I mean. Anyway, I think the new modes are great as they are, so thanks for that.

**Comment by Petervos2018** [comment]
> 
>     * PGMRX: select lights stay off

It's an expander, when placed to the right of PGMR , does it work ?

PEQ14 and LVCF 👍

**Comment by n0jo** [comment]
> It's an expander, when placed to the right of PGMR , does it work ?

It does. Thanks for pointing it out.

**Comment by mdemanett** [comment]
@n0jo thanks for testing!  The new build [here](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.33-test5) fixes those issues.

I've experimented with making the ports darker in dark and low-contrast modes, but to me it looks goofy because they don't contrast well with the background color around them.  I did darken them a shade in low-contrast.

**Comment by n0jo** [comment]
> I've experimented with making the ports darker in dark and low-contrast modes, but to me it looks goofy because they don't contrast well with the background color around them. 

@mdemanett I hear you. Sometimes stuff just doesn't work and form should follow function anyway IMHO. Great update.

**Comment by Eurikon** [comment]
For future reference:
The low contrast theme (old dark theme V1) that i created over here:
https://github.com/Eurikon/Bogaudio_Darktheme_V1
will be deleted.
As there is now an official version by Bogaudio. 
I will let the 0.6 version online for anyone that will need it.

**Comment by Eurikon** [comment]
Matt, are you going to announce this yourself at the forum?
Cause i am going to update my thread there about the old dark theme, but i don't want to spoil your announcement if there is any? :)

**Comment by mdemanett** [comment]
Nah, go ahead.  Might mention it's "coming soon" since it'll probably take a couple days for it to get built and uploaded to the library...

**Comment by mdemanett** [comment]
So it's live on the library, and announced on the forum.  Thanks again y'all for helping make it happen!
