### ISSUE TITLE
Peak Meter

### ISSUE THREAD

**Issue by jonheal** [bogaudio/BogaudioModules#50]
Hi, Matt,

Have you considered adding a peak indicator to you beautiful VU meter?

**Comment by mdemanett** [comment]
I hadn't thought of it...but it's a good idea.

**Comment by mdemanett** [comment]
This is implemented in the latest release -- I did a bit of guesswork about how they should behave, but I think it's reasonable.

**Comment by jonheal** [comment]
Matt,

 

I am probably stupid or blind, but I can’t see a new indicator on the VU meter when it detects a signal passing 0dB.

**Comment by mdemanett** [comment]
@jonheal You don't see a blue square above the usual ones?  At least when you hit with a transient -- the usual indication covers the peak if they're the same.

**Comment by jonheal** [comment]
OK, yes, I see that. Thanks.
