### ISSUE TITLE
sync walk to clock

### ISSUE THREAD

**Issue by joopvdl** [bogaudio/BogaudioModules#51]
Let's start by saying yours are some of my favorite modules.
I have a question about the two new Walk modules. Is it possible to sync those to a clock?

**Comment by mdemanett** [comment]
Do you mean have the rate follow a clock somehow?  Or have the output be stepped at the clock rate?

The second can be down by patching into a sample-and-hold (obvs).  I had an onboard function for that in an early version, but had to drop it for space reasons.

**Comment by joopvdl** [comment]
Yes, I meant the second one, steps at a clocked (or triggered) rate. That's
great for creating melodies. But, of course, sample and hold will also do
the trick.



Op di 14 mei 2019 om 01:09 schreef Matt Demanett <notifications@github.com>:
