### ISSUE TITLE
bug: LLFO Pulse output waveform

### ISSUE THREAD

**Issue by veryfungi** [bogaudio/BogaudioModules#52]
Hiya, I noticed when opening a saved patch with the LLFO waveforem set to pulse, it operates as a square wave, i.e. 50% duty cycle. If you click the selector to go back around to pulse it operates as intended. It's easy for me to replicate the problem. Excellent modules! Thanks so much for making them available!

**Comment by mdemanett** [comment]
I haven't been able to replicate it.  But:
  - Is the module updated to the latest (0.6.16, out today)?
  - Are you on Windows, Mac or Linux?
  - Maybe have a quicky patch where it happens?

**Comment by veryfungi** [comment]
Hi Matt, I found the bug in 6.14, but after I updated to 6.16 it is gone. I am running windows 7. Simply adding the module, setting the wave to pulse and saving then reopen caused the pulse output to operate like a square wave. But it's fixed now anyway. :)
