### ISSUE TITLE
another suggestion for the sequencer

### ISSUE THREAD

**Issue by MaZe6K** [bogaudio/BogaudioModules#53]
Hi! It's me again with the sequencer suggestions :)
I think it might be nice to be able to switch the range of the ADDR SEQ to -+5, -+3, -+1, 0-1, 0-5 and 0-10. Because especially when MIDI comes I will have to use an attenuator and offset each time (because the midi resolution is not fine enough to hit indiviual notes)
And I still think you should make the step length automatable and direction switchable with a gate. To make room for the inputs you could move the other inputs and controls a bit more up and down and closer together.
Please don't feel bugged by me, I'm just writing to you because these are already the nicest sequencers for my needs and with these additions I think they would be absolutely perfect.

**Comment by Petervos2018** [comment]
+- 10, +-5 ,+-1 for the range selectable via right-click menu would be great.

Greetings Peter

**Comment by Petervos2018** [comment]
From the code I presumed that you where making the range selectable. V1.1.18
And I love you for that...
Only problem is, it does not work...
As soon as I connect a clock to the clock the menu jumps back to +/-10V. 
And even when I select a different range (without a clock) it still is +/-10V.
Hope you find out why,

Greetings Peter

**Comment by mdemanett** [comment]
I see the problem using a real build of Rack and community build of the plugin...but don't see it (it works fine) in my dev build.  Which just means the fix I'm putting out now is a just a guess and may not be the answer.  Anyway, fingers crossed, it's queued up in the community system.

**Comment by Petervos2018** [comment]
To bad...
the blind fix does not solve the "problem" only range I can use is +-5V.
And in the right-click menu the top or bottom 4 ranges are selected simultaneously (when no clock is connected) like this : V1.1.19
![Add1119](https://user-images.githubusercontent.com/46076474/61151282-e05a6f80-a4e5-11e9-87d8-bc32ae356e3a.jpg)

**Comment by Petervos2018** [comment]
Well done and fast too 
1.1.20 solves all issues on W7.
Thank you.
Peter

**Comment by Petervos2018** [comment]
1.1.21 FIXED !
What can I say...
You are amazing, but you already knew that ;)

Thank you,
Peter
