### ISSUE TITLE
build fail with today's Rack build (v1)

### ISSUE THREAD

**Issue by davephillips** [bogaudio/BogaudioModules#55]
Fedora 23 Linux
VCV Rack v1.dev.6969390
GCC 5.3.1

Greetings ! Here's what's happening this morning:

https://pastebin.com/bcakGMKV

HTH,

dp

**Comment by tank-trax** [comment]
I get something similar

Debian Stretch 9.9
gcc version 6.3.0 
VCV Rack v1dev.6969390

https://pastebin.com/ggCN1esH

**Comment by mdemanett** [comment]
Should be fixed.

**Comment by tank-trax** [comment]
They built successfully on my end. Thanks!

**Comment by davephillips** [comment]
All good now, thank you ! :)
