### ISSUE TITLE
Bug V1: Mixers master mute have 3 states

### ISSUE THREAD

**Issue by Coirt** [bogaudio/BogaudioModules#58]
https://github.com/bogaudio/BogaudioModules/blob/v1/src/Mix4.hpp#L85
https://github.com/bogaudio/BogaudioModules/blob/v1/src/Mix8.hpp#L125

4 and 8 mixers have 3 states for master mute. This causes 3 presses to unmute, the channel mutes have a max value of `3.f` also but they are 1 press mute/unmute.

**Comment by mdemanett** [comment]
Fixed.
