### ISSUE TITLE
build error & resolution

### ISSUE THREAD

**Issue by davephillips** [bogaudio/BogaudioModules#6]
Linux Fedora 23
Rack 0.5.x

g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Isrc/dsp -Wsuggest-override -std=c++11 -c -o build/src/Reftone.cpp.o src/Reftone.cpp
src/Reftone.cpp: In member function ‘virtual void ReftoneDisplay::draw(NVGcontext*)’:
src/Reftone.cpp:162:22: error: ‘strlen’ was not declared in this scope
  if (strlen(frequency) < 5) {
                      ^
../../compile.mk:53: recipe for target 'build/src/Reftone.cpp.o' failed
make: *** [build/src/Reftone.cpp.o] Error 1

Solved by adding cstring to Reftone.cpp includes

**Comment by mdemanett** [comment]
Fixed -- thanks for the heads up.
