### ISSUE TITLE
Dgate - delay at 0 is still delayed

### ISSUE THREAD

**Issue by espenstoro** [bogaudio/BogaudioModules#61]
Hi.
I just noticed that the gate output still has an audible delay even when it is set to 0, which is also clearly visible on the scope when comparing it to the trigger signal. If I use something like Quantum by ML, there is no such delay from the gate or trigger output.
Example: Blue is the trigger signal from Quantum, and pink is Dgate, all triggered by the same clock.
Running Rack 0.6.2c on Windows 8.1. Plugin version 0.6.16.
![k756](https://user-images.githubusercontent.com/41498804/59507711-2521c500-8eac-11e9-80d8-888c13a9bc07.jpg)

**Comment by mdemanett** [comment]
Bug confirmed, good catch.  Will get a fix out soon.

**Comment by mdemanett** [comment]
Fixed.
