### ISSUE TITLE
Mix 4 / Mix 8 mute buttons can not be mapped.

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#64]
Hi Matt, in an effort to try and map the channel mute button to the uMap module from Ben Stoermelder.
I could not get this to work. 
I did have a small conversation with Ben, he could not find anything on his side. 
So I suggested to open an issue here to ask you. 

He did let me know the following when i asked him specifics: 

> The mute button parameter actually uses 4 different values (off=0, mute=1, solo=2, solo-on-mute=3) and values 2 and 3 are enabled by right-click. When mapping will work you’re going either to offset and scale or input 6,66V to get the parameter to “3” what means “solo”.

So, hopefully we can have this feature enabled, to can map the mute buttons :)

**Comment by mdemanett** [comment]
Fixed...but watch out that indeed the button takes four states, so if you map to a knob you'll get all four over the full CC range.  The upper two are both solo.
