### ISSUE TITLE
Bi-Polar signal for S&H - Feature Request

### ISSUE THREAD

**Issue by omricohenmusic** [bogaudio/BogaudioModules#65]
Hi!
I would love to have the option to have the S&H signal bi polar. Now, when not sending an external source, the generated signal has the range of 0/+10 volts, but it would be great to have something like the new options on the ADDR-SEQ, a few range options or only uni/bi polar options. Would something like this be possible?
Thanks!

**Comment by mdemanett** [comment]
Yeah, I can add that.

**Comment by mdemanett** [comment]
Done!

**Comment by omricohenmusic** [comment]
Thank you so much, it's brilliant!
