### ISSUE TITLE
Feature request: polyphonic modules

### ISSUE THREAD

**Issue by nesdnuma** [bogaudio/BogaudioModules#66]
Hello,

After a few sessions of work with VCV Rack, I see that I often use some Bogaudio modules such as the noise generator, the walk generator or the VCA and mixers (these latter ones because of the scale in dBs instead of linear as on many alternative mixers).

However it would be nice if the modules would be polyphonic. For the mixers, getting a polyphonic signal in a single input and spread the channels as if they arrived on individual inputs would be great.

Cheers.

**Comment by mdemanett** [comment]
Polyphonic support is coming, but no ETA yet.  Having a poly signal distribute across the mixer is an interesting idea...will look into it.

**Comment by Coirt** [comment]
In the meantime see[ here](https://vcvrack.com/plugins.html#bark) Poly Mix

**Comment by ptrumpet** [comment]
hey,  I've been testing the poly stuff on head.  quite happy.  I did make one unorthodox tweak, and that was to add a count for poly channels on the FM input of the osc as I was using FM without v/oct to do stuff.  Same could be applied to other osc's.

**Comment by mdemanett** [comment]
> hey, I've been testing the poly stuff on head. quite happy. I did make one unorthodox tweak, and that was to add a count for poly channels on the FM input of the osc as I was using FM without v/oct to do stuff. Same could be applied to other osc's.

Thanks for testing, glad the stuff is working.  I like the idea of that feature, will add it.
