### ISSUE TITLE
Bogaudio modules

### ISSUE THREAD

**Issue by blackearth2014** [bogaudio/BogaudioModules#7]
I just want to say great job on the development of your modules. I use them a lot in my projects. now that you have developed a VCA module, it is a long awaited complement to your DADSR(H) module that I wanted.

I am still trying to figure out the DADSR(H) module in whole, but it sounds nice. I will be waiting for a compressor/limiter in mono/stereo.

Great Job,

Thanks

**Comment by mdemanett** [comment]
Thank you for the kind words!

I'd like to make a compressor.  I'll see if I can mark this Feature Request.

**Comment by blackearth2014** [comment]
You have VCA, Envelops Generators, Offsets, Gate Delays and Etc. What you don't have that I personally feel that would enhance your modules is a VCF's, LFO's and VCO's Wavetable or Grandular Synthesis.

**Comment by mdemanett** [comment]
Finally released a compressor!  Would be glad to know what you think of it.

**Comment by blackearth2014** [comment]
The compressor is nice. I will put it through the paces these coming days. Also, is your limiter a brickwall limiter.

**Comment by mdemanett** [comment]
Yes, the limiter is a brickwall -- equivalent to setting the compressor's ratio to infinity.

**Comment by blackearth2014** [comment]
Thanks.
