### ISSUE TITLE
 Sequential Switches CV in is shifted by -0.62V ??

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#70]
Hi Matt,

> As a multiplexer, it routes an input to the output under control of the SELECT knob and CV. A 0-10V CV, divided into 8 equal divisions of 1.25V, controls the input selection. This value is summed with the knob setting; for example, setting the knob to 4 and inputting a 2.6V CV will send input 7 to the output. When the knob-plus-CV value exceeds 8, it wraps around.

This is not the way I measured it : 

in/out | Vmin | Vmax | range |  
-- | -- | -- | -- | --
1 | 0 | 0,62 | 0,62 |  
  | 9,37 | 10 | 0,63 | 1,25
2 | 0,62 | 1,87 | 1,25 |  
3 | 1,87 | 3,12 | 1,25 |  
4 | 3,12 | 4,37 | 1,25 |  
5 | 4,37 | 5,62 | 1,25 |  
6 | 5,62 | 6,87 | 1,25 |  
7 | 6,87 | 8,12 | 1,25 |  
8 | 8,12 | 9,37 | 1,25 |  

Also your example 4+2.6 does not work out , it is output 6 not 7 that is selected as seen in this pic : 

![Bog8inBug](https://user-images.githubusercontent.com/46076474/66124933-ff006c00-e5e5-11e9-842f-aef799dcb11c.png)

Greetings Peter.

**Comment by mdemanett** [comment]
There's both a bug with the way it uses the CV, and also the documentation is wrong.  The bug fix should make the voltage table correct.  But step 6 is the right output for the example.

Will fix in the next release.  Good catch, thank you.

**Comment by Petervos2018** [comment]
Works in 1.1.23 Thanks and Closed.

Peter.
