### ISSUE TITLE
Linear mode or 0 Hz for VCOs

### ISSUE THREAD

**Issue by ptrumpet** [bogaudio/BogaudioModules#71]
Great work with the modules.  They form the foundation for most of my patches, especially as I like working in the FM world.

would it be possible to have a VCO or LFO that can operate at 0 Hz, as I like to use a VCO as a signal processor via the FM input.  having a linear dial would also serve a similar purpose.

**Comment by mdemanett** [comment]
Not sure I entirely understand what you're looking for.  At 0HZ the oscillator would be stopped, which might be fun.  A negative voltage would run it backwards, I guess...literal through-zero modulation.  A ramp CV input from -5 to +5V would linearly move the output frequency from -N to +N HZ, where N is set by a knob?

FM-OP has a linear frequency knob (setting the frequency as a ratio of whatever is at v/oct), dunno if that helps.

**Comment by ptrumpet** [comment]
I managed to code up a test of linear freq for the base and i got it to work.  the idea is that at 0hz, the fm input simply modulates the main osc.  i run two osc's to L and R to get a phased stereo effect which you can tweak by deviationg from 0 hz.  at 0hz, the phasing is static.   next trick would be to apply fm mod to 8FO + the linear mod.  can send the diffs if you want or send a pull request.  Here's a snapshot of the use case.
![image](https://user-images.githubusercontent.com/6476326/66790693-921d9800-ef3c-11e9-8bef-77ecd3676993.png)

**Comment by mdemanett** [comment]
Yeah, diffs or a link to a branch if you push it up someplace or whatever.  It's a cool technique, definitely curious how it sounds.

**Comment by mdemanett** [comment]
The linear frequency change is in the latest release.
