### ISSUE TITLE
S&H normailization and ADDR trigger input

### ISSUE THREAD

**Issue by omricohenmusic** [bogaudio/BogaudioModules#72]
Hi!
I thought of a couple of things I wanted to share with you. About the S&H module, do you think it's possible to normalize the gates from the upper section to the lower section when no gate is connected to the lower one? It happens to me a lot that I use the same trigger for both sections and I thought maybe it would make sense to have then normalized. 
Another thing I thought about is concerning the ADDR-SEQ. It has a CV input for selecting the start of the sequence but maybe having the possibility to use a trigger or clock to move sequentially between the steps is a good idea? So for example, I have a four step sequence, and with each incoming trigger in the CV input, the sequence will start one step later instead of having to set another sequencer. Something in the right click menu I guess can help.

Anyway, thanks again!

**Comment by mdemanett** [comment]
Hey Omri,

The normalization makes sense, will add.

With ADDR-SEQ -- triggers on the CLOCK input advance the step...then whatever the SELECT knob/cv is doing adds on to that position, wrapping around.  But is that you mean?

**Comment by omricohenmusic** [comment]
Hi Matt,

Sorry for not being so clear... What I meant is, that when the Select CV input receives a trigger, it will move sequentially to the next step so if I have a 3 step sequence starting at step 1, it will play 1, 2, 3, and then a trigger will come in the Select CV input and it will play 2, 3, 4, and then again 3, 4, 5, and so on. So instead of using another sequencer to create this step by step, there will be an option to use a trigger for this.

Thanks again!

Omri Cohen

[https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abnExMEkyNGRPbWc&revid=0B8K00I2KYl3aT0xhRkhBcFU3Zk5YeWZrRFMrNitpRElSUWo0PQ]<http://omrico1983.wixsite.com/omricohencomposer>  <https://soundcloud.com/omricohencomposer/tracks> [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aMXU1emw5eVZIODA&revid=0B8K00I2KYl3aRHRtN0l5R2w2bG42UzQzMmF6WEVpL3JNMnpzPQ] <https://www.facebook.com/omricohenmusic/>   [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aY0ZmdDJVRTkyWVE&revid=0B8K00I2KYl3ab2s2Qm5XNDg5c1d0RlVyTE5XWUVwOXBHbERzPQ] <https://soundcloud.com/omricohencomposer/tracks>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aM2VYYkdMOTBibEE&revid=0B8K00I2KYl3aY2pJcTcycHhDc2ZkeEpsUHlVd25sS0RmQVpnPQ] <https://www.instagram.com/omricohencomposer/?hl=en>  [https://www.linkedin.com/in/omri-cohen-b01b70150/] <https://www.linkedin.com/in/omri-cohen-b01b70150/>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abkliN1pfQk5lSG8&revid=0B8K00I2KYl3aZ2Q5R0lINlVYZ0RDeWI4Um53Z3NSdG1La3NvPQ] <https://omricohencomposer.bandcamp.com/>


<https://www.facebook.com/omricohenmusic/>
<https://www.facebook.com/omricohenmusic/>

________________________________

**Comment by mdemanett** [comment]
> Hi Matt, Sorry for not being so clear... What I meant is, that when the Select CV input receives a trigger, it will move sequentially to the next step so if I have a 3 step sequence starting at step 1, it will play 1, 2, 3, and then a trigger will come in the Select CV input and it will play 2, 3, 4, and then again 3, 4, 5, and so on. So instead of using another sequencer to create this step by step, there will be an option to use a trigger for this. 

Ok, I think I get it, but to be sure: there's a context menu switch, that puts it in a mode where triggers at the select CV cycle the select through step offsets 0, 1, 3, ...7?

**Comment by omricohenmusic** [comment]
Yeah, exactly. So with each incoming trigger, the sequence will start on the next step. Does this make sense?

Omri Cohen

[https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abnExMEkyNGRPbWc&revid=0B8K00I2KYl3aT0xhRkhBcFU3Zk5YeWZrRFMrNitpRElSUWo0PQ]<http://omrico1983.wixsite.com/omricohencomposer>  <https://soundcloud.com/omricohencomposer/tracks> [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aMXU1emw5eVZIODA&revid=0B8K00I2KYl3aRHRtN0l5R2w2bG42UzQzMmF6WEVpL3JNMnpzPQ] <https://www.facebook.com/omricohenmusic/>   [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aY0ZmdDJVRTkyWVE&revid=0B8K00I2KYl3ab2s2Qm5XNDg5c1d0RlVyTE5XWUVwOXBHbERzPQ] <https://soundcloud.com/omricohencomposer/tracks>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aM2VYYkdMOTBibEE&revid=0B8K00I2KYl3aY2pJcTcycHhDc2ZkeEpsUHlVd25sS0RmQVpnPQ] <https://www.instagram.com/omricohencomposer/?hl=en>  [https://www.linkedin.com/in/omri-cohen-b01b70150/] <https://www.linkedin.com/in/omri-cohen-b01b70150/>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abkliN1pfQk5lSG8&revid=0B8K00I2KYl3aZ2Q5R0lINlVYZ0RDeWI4Um53Z3NSdG1La3NvPQ] <https://omricohencomposer.bandcamp.com/>


<https://www.facebook.com/omricohenmusic/>
<https://www.facebook.com/omricohenmusic/>

________________________________

**Comment by mdemanett** [comment]
> Yeah, exactly. So with each incoming trigger, the sequence will start on the next step. Does this make sense? 

Hey Omri, sorry I dropped off line here.  Anyway, that makes sense.  I think I'll do it, and also have RESET reset this subsequence as well as the main one, and have the SELECT knob set the length of the subsequence, when in this mode.  What do you think?

**Comment by omricohenmusic** [comment]
No worries Matt 🙂 Yes, that sounds amazing. So we will be able to not only to nudge the sequence by one step forward with a trigger but also select the maximum steps. Yes, that's really nice. Thanks again!

Omri Cohen

[https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abnExMEkyNGRPbWc&revid=0B8K00I2KYl3aT0xhRkhBcFU3Zk5YeWZrRFMrNitpRElSUWo0PQ]<http://omrico1983.wixsite.com/omricohencomposer>  <https://soundcloud.com/omricohencomposer/tracks> [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aMXU1emw5eVZIODA&revid=0B8K00I2KYl3aRHRtN0l5R2w2bG42UzQzMmF6WEVpL3JNMnpzPQ] <https://www.facebook.com/omricohenmusic/>   [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aY0ZmdDJVRTkyWVE&revid=0B8K00I2KYl3ab2s2Qm5XNDg5c1d0RlVyTE5XWUVwOXBHbERzPQ] <https://soundcloud.com/omricohencomposer/tracks>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aM2VYYkdMOTBibEE&revid=0B8K00I2KYl3aY2pJcTcycHhDc2ZkeEpsUHlVd25sS0RmQVpnPQ] <https://www.instagram.com/omricohencomposer/?hl=en>  [https://www.linkedin.com/in/omri-cohen-b01b70150/] <https://www.linkedin.com/in/omri-cohen-b01b70150/>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abkliN1pfQk5lSG8&revid=0B8K00I2KYl3aZ2Q5R0lINlVYZ0RDeWI4Um53Z3NSdG1La3NvPQ] <https://omricohencomposer.bandcamp.com/>


<https://www.facebook.com/omricohenmusic/>
<https://www.facebook.com/omricohenmusic/>

________________________________

**Comment by mdemanett** [comment]
Noting that that the S&H normalization released today.  The other thing is still in the works, hopefully fairly soon.

**Comment by omricohenmusic** [comment]
Oh nice, thank you!

On Nov 8, 2019 00:29, Matt Demanett <notifications@github.com> wrote:

Noting that that the S&H normalization released today. The other thing is still in the works, hopefully fairly soon.

**Comment by mdemanett** [comment]
The triggered mode for ADDR-SEQ (and 1:8, 8:1) has been released.

**Comment by omricohenmusic** [comment]
Thank you so much, it's beautiful!

Omri Cohen

[https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abnExMEkyNGRPbWc&revid=0B8K00I2KYl3aT0xhRkhBcFU3Zk5YeWZrRFMrNitpRElSUWo0PQ]<http://omrico1983.wixsite.com/omricohencomposer>  <https://soundcloud.com/omricohencomposer/tracks> [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aMXU1emw5eVZIODA&revid=0B8K00I2KYl3aRHRtN0l5R2w2bG42UzQzMmF6WEVpL3JNMnpzPQ] <https://www.facebook.com/omricohenmusic/>   [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aY0ZmdDJVRTkyWVE&revid=0B8K00I2KYl3ab2s2Qm5XNDg5c1d0RlVyTE5XWUVwOXBHbERzPQ] <https://soundcloud.com/omricohencomposer/tracks>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3aM2VYYkdMOTBibEE&revid=0B8K00I2KYl3aY2pJcTcycHhDc2ZkeEpsUHlVd25sS0RmQVpnPQ] <https://www.instagram.com/omricohencomposer/?hl=en>  [https://www.linkedin.com/in/omri-cohen-b01b70150/] <https://www.linkedin.com/in/omri-cohen-b01b70150/>  [https://docs.google.com/uc?export=download&id=0B8K00I2KYl3abkliN1pfQk5lSG8&revid=0B8K00I2KYl3aZ2Q5R0lINlVYZ0RDeWI4Um53Z3NSdG1La3NvPQ] <https://omricohencomposer.bandcamp.com/>


<https://www.facebook.com/omricohenmusic/>
<https://www.facebook.com/omricohenmusic/>

________________________________
