### ISSUE TITLE
8FO waveforms

### ISSUE THREAD

**Issue by XtremeSounds** [bogaudio/BogaudioModules#74]
Hi it would be nice if we could get a random waveform and also the ability to set a different waveform for each output

**Comment by mdemanett** [comment]
Good ideas, but no promises if it will happen, I'd have to redesign the panel (especially for the second bit).  Will think about it.

**Comment by mdemanett** [comment]
Stepped random waveform added, finally.

**Comment by XtremeSounds** [comment]
Nice thanks!
