### ISSUE TITLE
S&H: invert option/toggle

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#75]
Would it be possible to have an invert option or tiny toggle switch, for each one of the outputs independently?

On a side note:
The context menu looks a bit strange cluttered with all that same text.
Maybe this would look tidier:

__Normalized Noise__
blue
white
pink
red

-------------------------

__Normalized Range__
+/- 10V
+/-   5V
+/-   3V
+/-   1V
+/- 0V-10V

etc

**Comment by mdemanett** [comment]
For the invert, looks like it might fit but I'll have to see.

The menu suggestion is good; not sure there's a way to make a subheading like that (but there probably is).

**Comment by Eurikon** [comment]
I meant it to be underlined,   but it came out bold in the markup :)

**Comment by mdemanett** [comment]
S&H has invert buttons in the latest release.

I also changed the select-from-several type menu items into submenus....

**Comment by Eurikon** [comment]
Awesome , thanks Matt. 
I have also updated the dark mode svg for this module to reflect the new changes as well :) 
Thanks again!
