### ISSUE TITLE
Bool Not does not work as before in 1.1.23

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#77]
As title says W7.

Greetings Peter.

**Comment by mdemanett** [comment]
Good catch, thanks.

**Comment by Petervos2018** [comment]
You do all this work , making all your modules polyphonic, hours upon hours of work, finally you set it free, and the first reaction you get is .... nag nag nag BOOL does not work ;)
Thank you for ALL your modules and the polyphonic FMOP,  I know someone who is very happy.
Greetings Peter.

**Comment by Petervos2018** [comment]
Fixed in1.1.24.
Thanks. Closed
