### ISSUE TITLE
Monophonic L/R to stereo out should stay monophonic

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#78]
When I connect a monophonic L/R signal to a stereo in it should not multiply the output.
It works OK when I only connect the left input, but when I connect the right also the out signal becomes polyphonic, so I have 2x1channel in and 2x2channels out.
I don't think this is the right way to go. It doubles the CPU and makes new channels that should not be there.

![BogPolyBug-10112019](https://user-images.githubusercontent.com/46076474/68549927-25dc6a00-03fe-11ea-9bbd-52f6c3b4eb1c.png)

As you can see the Vu meter and the CLPR are OK, but the limiter compressor and noisegate are not.

Greetings Peter.

It probably has to do with normalizing a mono(L) input to both(L/R) outputs, which makes it hard to fix.

**Comment by fractalgee** [comment]
actually no other poly module I have tried does this so definitely should be fixable, so let's hope a fix is near :) I will close #85 as this is same.....

**Comment by mdemanett** [comment]
Fixed finally -- a stupid bug affected PRESSOR, LMTR and NSGT.  It should work as documented, now.

With CLPR I just forgot to make it polyphonic.

Thanks for the reports!

**Comment by therealkitman** [comment]
I thought I was going mad this afternoon with mono/poly issues on LMTR 1.1.23. Looks like @Petervos2018 beat me to the punch in reporting it :smiley: 

![image](https://user-images.githubusercontent.com/14888092/69004167-ab55a200-0949-11ea-9ca2-4bca1a295843.png)

**Comment by fractalgee** [comment]
Sadly Pressor still has this issue as well in 1.1.23, so fixed is it not yet I am afraid.... I fed a mono left and a mono right in and get a 2 channel Poly left and right respectively on the outs. That is not the expected ```input_channels == output_channels```

**Comment by fractalgee** [comment]
@therealkitman : The fix is done, just waiting on a new 1.1.24 build to pop up on plugin manager

**Comment by therealkitman** [comment]
> The fix is done

Thanks. Yep, waiting for 1.1.24.

**Comment by Petervos2018** [comment]
Version 1.1.24  PM.
It looks like this is fixed now, thank you Matt.
Closing.
