### ISSUE TITLE
Crash VCV Limiter related ? W7 

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#79]
[1.355 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
15: ZN4rack10appDestroyEv 0x456435
14: raise 0xfdc816f0
13: abort 0xfdc8537c
12: ZN8bogaudio3dsp15CICInterpolatorC1Eii 0x8276e6c
11: ZN8bogaudio3dsp15CICInterpolatorC1Eii 0x8276e6c
10: ZN8bogaudio3dsp9Amplifier8setLevelEf 0x8273e3c
9: ZN8bogaudio4Lmtr14processChannelERKN4rack6engine6Module11ProcessArgsEi 0x826ecbc
8: ZN8bogaudio8BGModule7processERKN4rack6engine6Module11ProcessArgsE 0x826d57c
7: ZN4rack6engine6Module6configEiiii 0x49d774
6: ZN4rack6engine6EngineD2Ev 0x49f7f2
5: atomic_flag_test_and_set_explicit 0x6fd39a40
4: pthread_create_wrapper 0x64944a10
3: srand 0xfdc440cc
2: ftime64_s 0xfdc46ce0
1: BaseThreadInitThunk 0x77415560
0: RtlUserThreadStart 0x77673840

**Comment by mdemanett** [comment]
I turned up an initialization bug that could possibly cause this...but it's hard to be sure.

**Comment by Petervos2018** [comment]
[0.980 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
15: ZN4rack10appDestroyEv 0x456435
14: raise 0xfdf716f0
13: abort 0xfdf7537c
12: ZN8bogaudio3dsp15CICInterpolatorC1Eii 0x82470ac
11: ZN8bogaudio3dsp15CICInterpolatorC1Eii 0x82470ac
10: ZN8bogaudio3dsp9Amplifier8setLevelEf 0x824407c
9: ZN8bogaudio4Lmtr14processChannelERKN4rack6engine6Module11ProcessArgsEi 0x8222498
8: ZN8bogaudio8BGModule7processERKN4rack6engine6Module11ProcessArgsE 0x823ce3c
7: ZN4rack6engine6Module6configEiiii 0x49d774
6: ZN4rack6engine12EngineWorker3runEv 0x49ecde
5: atomic_flag_test_and_set_explicit 0x6fd39a40
4: pthread_create_wrapper 0x64944a10
3: srand 0xfdf340cc
2: ftime64_s 0xfdf36ce0
1: BaseThreadInitThunk 0x77915560
0: RtlUserThreadStart 0x77a73710

1.1.24 did not fix this.

Here is the patch, and as with all bug hunting this works most of the time without an error but sometimes it gives a crash when I open rack with this patch loaded. ( just to make it extra hard to find ;)

[Barbieri 5 step - 21102019.zip](https://github.com/bogaudio/BogaudioModules/files/3869356/Barbieri.5.step.-.21102019.zip)

Greetings Peter

**Comment by Petervos2018** [comment]
NOTE : I just tried opening and closing rack 10+ times and no crash at all, let us say it's fixed.
Although it is not really....

**Comment by mdemanett** [comment]
I tried that too, and no crashes.  That doesn't mean it's not there.

**Comment by mdemanett** [comment]
About 1 minute after I wrote the last message, I started getting the crash.

**Comment by mdemanett** [comment]
I think it's fixed (for real).  Thanks again for the reports and the patch.

**Comment by Petervos2018** [comment]
I think 1.1.25 solved this  (I f not I reopen this with a vengeance ;) Thank you Matt

Closed.
