### ISSUE TITLE
SwitchMix88

### ISSUE THREAD

**Issue by Eurikon** [bogaudio/BogaudioModules#80]
Hi Matt,
can we have this:
![switch-mix88](https://user-images.githubusercontent.com/40998416/68678757-d497bc00-055e-11ea-9ee5-e70797ac67f4.png)

according to these specs:
http://www.hinton-instruments.co.uk/paprod/modular/switchmix/switchmix_manual1.pdf

A switch mixer, with precision adder functionality.
I would be happy if it was for CV only, but if you can manage to have it working for both CV & audio that would be total bonus!

The switch knobs lit up green when receiving a positive signal / red for negative.
Amber for audio.
The cut knobs near the output jacks could lit up from same as your mixer channel knobs do, from min to max levels, and red when pressed down to cut signal.

I hope you will be interested!

**Comment by Eurikon** [comment]
Oh yeah.. and midi mapping capability for all switches ;)

**Comment by Eurikon** [comment]
different layout:
![switch-mix88_b](https://user-images.githubusercontent.com/40998416/68685678-c2bc1600-056a-11ea-918b-275ae413bbc4.png)

**Comment by mdemanett** [comment]
Interesting...will have to think about it.

**Comment by Eurikon** [comment]
Hi Matt, just a heads-up that this module has been developed by another developer.
But still thank you for your interest and responding to my request :) 
![InterMix](https://user-images.githubusercontent.com/40998416/69920264-f9a88c00-1485-11ea-9a48-fe3ca0ef37eb.png)

**Comment by mdemanett** [comment]
Ah cool!

**Comment by mdemanett** [comment]
I went a bit crazy with the matrix mixers, here's the family in the next release:
![Screen Shot 2019-12-16 at 9 38 51 PM](https://user-images.githubusercontent.com/49971/70960324-b4bb5280-204c-11ea-89f9-ab887a12392c.png)

**Comment by Deevje** [comment]
You went beyond anything I could have wished for, this looks amazing! Can't wait to try them out, especially the 16x16 switch!

**Comment by Eurikon** [comment]
Holy snazzles Matt! hahaha more choice , more power! wheeeep wheeeeeeep! :D
