### ISSUE TITLE
DADSR (H) & (H) + : Buttons not working.

### ISSUE THREAD

**Issue by Anthony-Lockwood** [bogaudio/BogaudioModules#81]
I have noticed that now I am unable to trigger an envelope with the trigger button. Likewise I am unable to change the shape of the attack, decay and release stages with their buttons.

I can only do this procedure now with a cable plugged into the trigger.

Edit: Looping will work only when a cable is plugged into trigger. 

All the best and thank you.

**Comment by bubbleandsquawk** [comment]
I am experiencing this same issue with Shaper too

**Comment by mdemanett** [comment]
Bug confirmed...fix should be out fairly soon.

**Comment by mdemanett** [comment]
Fixed.
