### ISSUE TITLE
Something is Off with FM OP 1.1.23

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#82]
Hi Matt,

It sounds glitchy after update 1.1.23.
I included a zip in which I have 2 mp3s and the vcv file the one called right is made with1.1.22 the wrong one is made with 1.1.23.
Hope you hear what I hear and are able to fix it.

Greetings Peter.
[FMOPWrong - 13112019.zip](https://github.com/bogaudio/BogaudioModules/files/3843552/FMOPWrong.-.13112019.zip)

**Comment by mdemanett** [comment]
I made a change in the last release to reduce the rate at which some parameters are recalculated from every 100 samples to every 10ms regardless of sample rate.  This is meant to save CPU.  

I pushed a change to set that back to how it was.  Can you please try it?  If the problem goes away, then this was to blame; if not, then at least this is ruled out.

**Comment by Petervos2018** [comment]
>I pushed a change to set that back to how it was. Can you please try it?

I'd love to but I don't know how, I'm just a user, I can/do not build binaries.

Greetings Peter.

**Comment by mdemanett** [comment]
> I'd love to but I don't know how, I'm just a user, I can/do not build binaries.

Ok cool...I'm going to put out a bugfix release pretty soon, we'll hope this is it.

**Comment by Petervos2018** [comment]
Yep I think that 1.1.24 solves the glitchy-ness ;)
Thanks, closed.
