### ISSUE TITLE
Pressor 1.1.23 reports poly outs when mono ins are patched

### ISSUE THREAD

**Issue by fractalgee** [bogaudio/BogaudioModules#85]
Rack 1.1.6, MacOS X 10.11.6, BogAudio 1.1.23

I have the left and right out of Pressor as Poly cables, even though i feed in only 2 mono signals (single channel). That is not correct for poly behavior, as it should be 

```channels_out == channels_in```

**Comment by Petervos2018** [comment]
See my #78

**Comment by fractalgee** [comment]
This is same as #78 so closing this
