### ISSUE TITLE
Matrix88 Feature Request

### ISSUE THREAD

**Issue by Deevje** [bogaudio/BogaudioModules#86]
Hey there,
I would like to request a feature for the Matrix88, it would be really great if the knobs lit up in the same colors used for the mute/solo buttons on your mixers, towards orange for the inverting negative value side, towards green for the attenuating or positive value side (or maybe the possibility to choose the knobs’ function in the menu, like the volts range options in your ADDR sequencer).
I am trying to build an emulation of an EMS VCS3 Synthi and would like to use as many Bogaudio modules for it as I can, since they give a nice uniform feel and are very nice to work with. Only difficulty I had with the Matrix88 was, I couldn't see from a bit of distance where the dials are at, or which ones are in use at all.
Scrolling through the requests on here I found that someone already posted a similar question a few days ago concerning a matrix switch mixer with color lit buttons indicating its state/function, based on a Eurorack module by Hinton Electronics, but I doubt we need a new module to get this functionality, the Matrix88 seems to be almost there already :)
Also, the switch mixer request had a mockup showing inputs on the bottom feeding to the outputs on the right, I would love for it to stay oriented the way it is now, which more resembles the Synthi's patch matrix.
![Synthi Patch Matrix](https://user-images.githubusercontent.com/57831348/68992360-96eea800-086a-11ea-91e0-b0cde8717828.jpg)
I hope you can make this happen!
Kind regards,
Deev

**Comment by mdemanett** [comment]
Like I said on the related ticket -- good idea, but let me think on it.

**Comment by mdemanett** [comment]
So this is happening in the next release...see the screenshot on #80.

**Comment by Deevje** [comment]
Thank you so much for putting in the time and effort! I'm really looking forward to trying these out! This will make a lot of my patches so much more streamlined!
