### ISSUE TITLE
Pressor weird behaviour 1.1.24

### ISSUE THREAD

**Issue by Petervos2018** [bogaudio/BogaudioModules#87]
Hi Matt,

Ok this is hard to explain.
Load the patch I have provided, choose the right audio settings for you in audio-8, close Rack.
It is important that you close RACK.
Start Rack, click the (un)mute button of the busdepot (top).

It takes 2 to 3 seconds before the sound starts to come trough Pressor.

Greetings Peter.
[Pressor weird - 20112019.zip](https://github.com/bogaudio/BogaudioModules/files/3870146/Pressor.weird.-.20112019.zip)

**Comment by mdemanett** [comment]
Having trouble reproducing this one....

**Comment by Petervos2018** [comment]
I thought you might, this one is easier, same deal load patch set the right audio close rack.
Open rack and un-mute the master... there will be no sound.
Until you "pump up the volume"

[Pressor weird MASTER - 20112019.zip](https://github.com/bogaudio/BogaudioModules/files/3874290/Pressor.weird.MASTER.-.20112019.zip)

**Comment by midiguru** [comment]
In Windows 7, when I load a patch containing Pressor on the output bus, there's no audio output at all until I delete it and then ctrl-Z to undo the deletion. This is consistent, repeatable behavior in 1.1.24.

**Comment by midiguru** [comment]
...and now, after being a consistent problem for days, it has suddenly become intermittent.

**Comment by mdemanett** [comment]
Think I figured it out...it's the same underlying problem as #79 and seems to be fixed by the fix for that.  Thanks for the patches and reports, I was finally able to reproduce it.

I'm requesting a build now to get that fix out, so it should be available in a few days.

**Comment by Petervos2018** [comment]
I think 1.1.25 solves this, Thank you Matt.

Closed
