### ISSUE TITLE
Request/Suggestion - small sine oscillator derived from XCO

### ISSUE THREAD

**Issue by MaZe6K** [bogaudio/BogaudioModules#88]
Hi there!

I was wondering if you might consider to add a small VCO based on the sine oscillator from the XCO to your collection.
The reason I ask this is that there are almost no oscillators with phase control available for VCV Rack, and I sometimes would really like to have a small sine oscillator with phase control and FM capabilities. The sine oscillator on the XCO is just perfect for those tasks, but the XCO takes up much screen estate, so it would be very nice to have this as a separate small VCO, especially for drums and percussive sounds that might use 2 or 3 of those with a few envelopes.

I hope you like the idea of that :) if not, no worries - your collection is pretty great either way.

**Comment by mdemanett** [comment]
It's an interesting idea.

I'm not super sure what phase control would be good for -- on XCO, it adjusts the phase relative to the other waves, which are exactly the same frequency, and thus it changes the shape of the mixed waveform.  On a single-waveform oscillator offsetting the phase wouldn't change the sound (unless you're syncing it).  Maybe I don't understand what you're looking for?

**Comment by MaZe6K** [comment]
I mainly want to sync it to a trigger to get consistent bassdrums. 
When making a Bassdrum with one oscillator it helps to control the click of the attack transient, if you use two oscillators with pitch mod envelopes synced to a trigger and move the phases you can get a nice variety of consistent bassdrum sounds that are otherwise not achievable/controllable.
Add FM to the mix and you have a really nice and versatile drum synth.

**Comment by mdemanett** [comment]
Cool, that makes sense.  How important would CV control over the phase be?  Thinking about how much stuff will fit on a 3hp panel.

**Comment by MaZe6K** [comment]
I would suggest to do it without CV control for the phase, at least I don't have a use case for that yet and the size seems more important to me and 3HP sounds very good :)
I hope you can fit the other options though (lin and exp FM and feedback) - it will get very crammed already, but also be a great addition for FM synthesis in general.

**Comment by glocke01** [comment]
<blockquote>I mainly want to sync it to a trigger to get consistent bassdrums.</blockquote>
Doesn't the sync input on the VCO allow this?

**Comment by MaZe6K** [comment]
@glocke01 
The VCO doesn't have phase control, so it can only be restarted at the inital 0-crossing.
@mdemanett 
If 3hp is too small maybe 6hp might also be ok. Maybe then with 2 FM inputs - would be cool for drums and also would be a great addition for FM synthesis.
But do or don't do what you like and what you think is best for your plugin collection.

If I had any C++ skills I would probably try to add a phase control to all my favourite oscillators - it's unfortunately a bit underrated I think :)

**Comment by MaZe6K** [comment]
oh... I have totally overlooked that you have already added something... :)
Very cool! Looking forward to seeing it in my Rack! Thank You!

**Comment by mdemanett** [comment]
@MaZe6K Yeah these guys are coming soon, maybe in about a week:

![Screen Shot 2019-12-15 at 11 07 53 PM](https://user-images.githubusercontent.com/49971/70878557-f76b2500-1f8f-11ea-90b2-8261f78e79ab.png)

Thanks for the suggestion!

**Comment by MaZe6K** [comment]
Hi! 
I just wanted to tell you that I am now actually succesfully using the Sine module for nice and consistent kicks and thank you again!
If you want you can check out the first recording with it here:
https://www.youtube.com/watch?v=3JGmI-NapWs

**Comment by mdemanett** [comment]
That's awesome!  I really like the track!
