### ISSUE TITLE
BGA AD always looping

### ISSUE THREAD

**Issue by Revheim** [bogaudio/BogaudioModules#89]
BGA AD will loop it's envelope for as long as gate is held even if loop mode is not activated.
If the gate is equal to or longer than the cycle-time of the envelope, it will loop.

**Comment by mdemanett** [comment]
That's actually by design.  If loop mode is on, it loops regardless of the gate.  Otherwise yes it retriggers immediately on cycle end if the gate is high.

For an AD envelope that that runs once per gate, you can use ADSR and turn sustain to zero.

**Comment by mdemanett** [comment]
I thought more about this and decided the default behavior is pretty weird...I added an option to disable the retriggering.  In the next release.

**Comment by Revheim** [comment]
Thats brilliant, thanks =)
