### ISSUE TITLE
DGate.svg should be DGATE.svg

### ISSUE THREAD

**Issue by davephillips** [bogaudio/BogaudioModules#9]
Fedora 23 Linux
Rack 0.5.x

The module is looking for DGATE.svg, the case matters on Linux. :)
And thank you very much for your excellent modules !

**Comment by mdemanett** [comment]
Doh, oops.

I'll fix that and put out an updated release soon.

Meantimes, if you want a workaround, it should work to rename that file where it lives in the Rack plugin directory, which should be ```~/.Rack/plugins/Bogaudio/res/DGate.svg```.  When the plugin eventually updates, the files will be deleted and replaced, so it won't hurt anything.

Thank you for the report.  Glad you like the modules!
