### ISSUE TITLE
FM-OP Feedback CV not working?

### ISSUE THREAD

**Issue by briansorahan** [bogaudio/BogaudioModules#91]
I started making a patch today with FM-OP, was tweaking the Feedback knob manually and enjoying what I was hearing, so wanted to wire it up to an envelope. The CV Input seemed to be having 0 effect. Am I crazy? Is there something I'm missing?

Thanks for the wonderful modules BTW!!

**Comment by Petervos2018** [comment]
The feedback knob becomes an attenuator so you have to open it when you use cv input.

**Comment by mdemanett** [comment]
What Peter said...most of the CVs in this plugin work that way.

**Comment by briansorahan** [comment]
Thanks! I'll give this a go sometime this week
