### ISSUE TITLE
VCV Crash when opening DGate

### ISSUE THREAD

**Issue by ajbmorris** [bogaudio/BogaudioModules#92]
Hi guys - opening DGate in the attached patch crashes VCV Rack (opening it in an empty workspace is fine) - not sure what is causing it....
[fun24 tiny tricks3.zip](https://github.com/bogaudio/BogaudioModules/files/3908482/fun24.tiny.tricks3.zip)

**Comment by ajbmorris** [comment]
hmm changed a few gate times in the patch and now it seems to be loading ok! Weird!

**Comment by Petervos2018** [comment]
I'm on W7 and opening the patch and adding 1 (or more) D-Gates does NOT crash rack.
Just for info to help bug hunting.

**Comment by ajbmorris** [comment]
Should have clarified this is on windows10 64bit here

**Comment by ajbmorris** [comment]
the crash happened on selecting the module in the module browser

**Comment by mdemanett** [comment]
I couldn't replicate either on mac or windows -- doesn't mean it doesn't happen.  @ajbmorris next time it happens, Rack should write out a log.txt file under Documents/Rack -- if so could you paste here -- be sure to grab it right after the crash -- that will usually show a trace of the crash and might provide a clue.

**Comment by ajbmorris** [comment]
[log crash 191206.txt](https://github.com/bogaudio/BogaudioModules/files/3932137/log.crash.191206.txt)
Ok it's done it again in a different patch (attached with the log file)
[autosave-v1.zip](https://github.com/bogaudio/BogaudioModules/files/3932142/autosave-v1.zip)

**Comment by ajbmorris** [comment]
as before restarting same patch and it loads fine...

**Comment by mdemanett** [comment]
The log gave me the clue I needed, probably -- I still can't duplicate the crash, but I did find a likely culprit.  Fix will be in the next release, hopefully in a week or so.

**Comment by ajbmorris** [comment]
thanks Matt - and thanks for the great modules btw!

**Comment by Petervos2018** [comment]
Just got a crash when I wanted to add a Dgate module : 

[577.643 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
34: ZN4rack10appDestroyEv 0x456435
33: gai_strerrorW 0x739800
32: _C_specific_handler 0x76eb71cc
31: _chkstk 0x76ecbe00
30: RtlInitializeResource 0x76e9fed0
29: KiUserExceptionDispatcher 0x76ecb510
28: ZN8bogaudio5DGate23shouldTriggerOnNextLoadEv 0x82997cc
27: ZN8bogaudio19TriggerOnLoadModule10dataToJsonEv 0x82c0590
26: ZN4rack6engine6Module6toJsonEv 0x49cfc0
25: ZN4rack7history9ModuleAdd9setModuleEPNS_3app12ModuleWidgetE 0x4860a6
24: ZN4rack3app11AudioWidget12setAudioPortEPNS_5audio4PortE 0x49839c
23: ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE 0x75cbc0
22: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
20: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
19: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3ed4
18: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
17: ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE 0x7530d0
16: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
15: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
14: ZN4rack7updater17isUpdateAvailableEv 0x45914e
13: glfwPlatformUnlockMutex 0x4d78ae
12: TranslateMessageEx 0x76d797e0
11: CallWindowProcW 0x76d73a04
10: CallWindowProcW 0x76d73a04
9: glDebugEntry 0xf236a170
8: TranslateMessageEx 0x76d797e0
7: TranslateMessage 0x76d795a8
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x76c55560
0: RtlUserThreadStart 0x76eb3710

Greetings Peter.

**Comment by mdemanett** [comment]
@Petervos2018 thanks for the trace -- looks like the same problem that's already fixed, but more reports are helpful.  The release with the fix is coming shortly, at last.

**Comment by mdemanett** [comment]
The release is out, let me know if you all get this again.
