### ISSUE TITLE
Number of polyphonic output channels on oscilaltors like FM-OP

### ISSUE THREAD

**Issue by Stubs42** [bogaudio/BogaudioModules#93]
Hi,
I encountered a problem when trying a matrix FM setup with a few fm-ops (and others of your collection).
When polyphonic cables are connected the number of output channels seems to be max(#cv in channels, #fm channels). Now when seting up a polyphonic fm matrix (I used 8) using the maxtrix this will result in matrix88 sending 8 channels to each fm input of each of the oscillators.
When sending 3 polyphonic v/oct it generates 8 channel output using v/oct 0 for channel 4-8.
I propose not to use the number of fm in channels to define the number of outputs.
In my case I had to use an additional module to limit the number of fm channels to the same number of v/oct channels to get rid of those unwanted voices 4-8 just playing C4.
Don't know whether I was able to explain my problem.
Hope so though.

Here is screenshot of the fm matrix setup. The input triggers and v/Oct have just 3 channels.
The specific value at the left and the 8 Toly Pools are used as a workaround to avoid these not wanted output channels 4-8 by limitting the fm channels from the matrix to 3 channels.
![Screenshot](https://user-images.githubusercontent.com/52674858/69953364-60b35880-14f9-11ea-8348-eed7b4cd5480.png)

**Comment by mdemanett** [comment]
I see what's going on...will look into a fix.  I think you're right that the fix is that it can't use both v/oct and FM to calculate the channels.

**Comment by mdemanett** [comment]
The fix is released as of today.
