### ISSUE TITLE
request: wrapping/periodic boundary conditions on walk, walk2

### ISSUE THREAD

**Issue by glocke01** [bogaudio/BogaudioModules#94]
It would probably require a right-click menu option, but it would be useful to have an option that allowed the random walk modules to "wrap around" from min to max instead of "bouncing" against the walls (in math speak, this is aka periodic boundary conditions). An example application, what makes me request it, is to send to the input of NYSTHI vector mixer azimuth input, but also potentially useful for sending phase offsets to 8FO. Maybe not too widely useful but probably easy to add.

**Comment by mdemanett** [comment]
Could be fun, let me think about it.

**Comment by mdemanett** [comment]
I think this one isn't going to happen, sorry!

**Comment by glocke01** [comment]
No worries. I'm loving your (relatively) new VCF's. In particular, the bandpass filter is unique in the VCV ecosystem for being able to get arbitrarily fine/narrow without self oscillation, so now you can get "Duracell" filter pings that are common in digital synths but have been hard to get in VCV previously. I'm especially excited about it being polyphonic, because now we have a bank of bpfs with arbitrary cutoff, Q, and level which allows serious modal synthesis. I bought a hardware SMR with ideas of using it in this way and it's totally unsuitable (this was before I found VCV and well before Prism was released). 

Anyway, BogAudio is awesome and apologies aren't necessary <3
