### ISSUE TITLE
Build error [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [bogaudio/BogaudioModules#96]
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Isrc -Isrc/dsp -c -o build/src/Pressor.cpp.o src/Pressor.cpp
In file included from src/menu.cpp:2:
src/menu.hpp:10:7: error: 'function' in namespace 'std' does not name a template type
   10 |  std::function<bool()> _check;
      |       ^~~~~~~~
src/menu.hpp:4:1: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?
    3 | #include "rack.hpp"
  +++ |+#include <functional>
    4 |
src/menu.hpp:11:7: error: 'function' in namespace 'std' does not name a template type
   11 |  std::function<void()> _set;
      |       ^~~~~~~~
src/menu.hpp:11:2: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?
   11 |  std::function<void()> _set;
      |  ^~~
src/menu.hpp:13:41: error: 'std::function' has not been declared
   13 |  OptionMenuItem(const char* label, std::function<bool()> check, std::function<void()> set)
      |                                         ^~~~~~~~
src/menu.hpp:13:49: error: expected ',' or '...' before '<' token
   13 |  OptionMenuItem(const char* label, std::function<bool()> check, std::function<void()> set)
      |                                                 ^
src/menu.hpp: In constructor 'bogaudio::OptionMenuItem::OptionMenuItem(const char*, int)':
src/menu.hpp:14:4: error: class 'bogaudio::OptionMenuItem' does not have any field named '_check'
   14 |  : _check(check)
      |    ^~~~~~
src/menu.hpp:14:11: error: 'check' was not declared in this scope
   14 |  : _check(check)
      |           ^~~~~
src/menu.hpp:15:4: error: class 'bogaudio::OptionMenuItem' does not have any field named '_set'
   15 |  , _set(set)
      |    ^~~~
src/menu.hpp:15:9: error: 'set' was not declared in this scope; did you mean 'std::set'?
   15 |  , _set(set)
      |         ^~~
      |         std::set
In file included from C:/msys64/mingw64/include/c++/9.2.0/set:61,
                 from ../../include/midi.hpp:5,
                 from ../../include/rack.hpp:15,
                 from src/menu.hpp:3,
                 from src/menu.cpp:2:
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_set.h:94:11: note: 'std::set' declared here
   94 |     class set
      |           ^~~
In file included from src/menu.cpp:2:
src/menu.hpp: In member function 'virtual void bogaudio::OptionMenuItem::onAction(const rack::event::Action&)':
src/menu.hpp:21:3: error: '_set' was not declared in this scope
   21 |   _set();
      |   ^~~~
src/menu.hpp: In member function 'virtual void bogaudio::OptionMenuItem::step()':
src/menu.hpp:26:15: error: '_check' was not declared in this scope
   26 |   rightText = _check() ? "✔" : "";
      |               ^~~~~~
src/menu.hpp: At global scope:
src/menu.hpp:31:45: error: 'std::function' has not been declared
   31 |  BoolOptionMenuItem(const char* label, std::function<bool*()> get)
      |                                             ^~~~~~~~
src/menu.hpp:31:53: error: expected ',' or '...' before '<' token
   31 |  BoolOptionMenuItem(const char* label, std::function<bool*()> get)
      |                                                     ^
src/menu.hpp: In lambda function:
src/menu.hpp:32:43: error: 'get' was not declared in this scope; did you mean 'std::get'?
   32 |  : OptionMenuItem(label, [=]() { return *(get()); }, [=]() { bool* b = get(); *b = !*b; })
      |                                           ^~~
      |                                           std::get
In file included from C:/msys64/mingw64/include/c++/9.2.0/bits/unique_ptr.h:37,
                 from C:/msys64/mingw64/include/c++/9.2.0/memory:80,
                 from ../../include/window.hpp:5,
                 from ../../include/rack.hpp:13,
                 from src/menu.hpp:3,
                 from src/menu.cpp:2:
C:/msys64/mingw64/include/c++/9.2.0/tuple:1341:5: note: 'std::get' declared here
 1341 |     get(const tuple<_Elements...>&& __t) noexcept
      |     ^~~
In file included from src/menu.cpp:2:
src/menu.hpp: In lambda function:
src/menu.hpp:32:72: error: 'get' was not declared in this scope; did you mean 'std::get'?
   32 |  : OptionMenuItem(label, [=]() { return *(get()); }, [=]() { bool* b = get(); *b = !*b; })
      |                                                                        ^~~
      |                                                                        std::get
In file included from C:/msys64/mingw64/include/c++/9.2.0/bits/unique_ptr.h:37,
                 from C:/msys64/mingw64/include/c++/9.2.0/memory:80,
                 from ../../include/window.hpp:5,
                 from ../../include/rack.hpp:13,
                 from src/menu.hpp:3,
                 from src/menu.cpp:2:
C:/msys64/mingw64/include/c++/9.2.0/tuple:1341:5: note: 'std::get' declared here
 1341 |     get(const tuple<_Elements...>&& __t) noexcept
      |     ^~~
In file included from src/menu.cpp:2:
src/menu.hpp: In constructor 'bogaudio::BoolOptionMenuItem::BoolOptionMenuItem(const char*, int)':
src/menu.hpp:32:90: error: no matching function for call to 'bogaudio::OptionMenuItem::OptionMenuItem(const char*&, bogaudio::BoolOptionMenuItem::BoolOptionMenuItem(const char*, int)::<lambda()>, bogaudio::BoolOptionMenuItem::BoolOptionMenuItem(const char*, int)::<lambda()>)'
   32 |  : OptionMenuItem(label, [=]() { return *(get()); }, [=]() { bool* b = get(); *b = !*b; })
      |                                                                                          ^
src/menu.hpp:13:2: note: candidate: 'bogaudio::OptionMenuItem::OptionMenuItem(const char*, int)'
   13 |  OptionMenuItem(const char* label, std::function<bool()> check, std::function<void()> set)
      |  ^~~~~~~~~~~~~~
src/menu.hpp:13:2: note:   candidate expects 2 arguments, 3 provided
src/menu.hpp:9:8: note: candidate: 'bogaudio::OptionMenuItem::OptionMenuItem(const bogaudio::OptionMenuItem&)'
    9 | struct OptionMenuItem : MenuItem {
      |        ^~~~~~~~~~~~~~
src/menu.hpp:9:8: note:   candidate expects 1 argument, 3 provided
src/menu.hpp:9:8: note: candidate: 'bogaudio::OptionMenuItem::OptionMenuItem(bogaudio::OptionMenuItem&&)'
src/menu.hpp:9:8: note:   candidate expects 1 argument, 3 provided
make: *** [../../compile.mk:69: build/src/menu.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by mdemanett** [comment]
Fixed.

**Comment by SteveRussell33** [comment]
Fix good. Closing.
