### ISSUE TITLE
Adjusting slope in ANALYZER-XL

### ISSUE THREAD

**Issue by vcvrackideas** [bogaudio/BogaudioModules#97]
Hi! Your awesome analyzer-xl would be more awesome if you could add configurable slope parameter into right-click menu (I mean those sliders like mindmelder mixer has in its right click menus) with db\oct label. For example it would be handy to adjust default falling slope to the linear one which for me is pretty much easy to follow when adjusting overall mix. Voxengo SPAN has this feature and I believe other VST analyzers as well.

**Comment by mdemanett** [comment]
I'll look into that...

**Comment by mdemanett** [comment]
There are linear plots for frequency and amplitude, now.
