### ISSUE TITLE
mute8 toogle possibilitiy

### ISSUE THREAD

**Issue by matthleg** [bogaudio/BogaudioModules#98]
Hello, first thanks for your fantastic work.
I would really enjoy if, in your Mute8 you would add in the right click menu an option "toogle/momentary" to have the possibility to stay in mute when you send a trig (and an-mute with a second trig). 
Please think about it
Have a nice week.
Matthieu.

**Comment by mdemanett** [comment]
I'll take a look!

**Comment by mdemanett** [comment]
In the new release.
