### ISSUE TITLE
VCV crash when disconnecting cable from Stack

### ISSUE THREAD

**Issue by skybrian** [bogaudio/BogaudioModules#99]
Unfortunately I don't know how to reproduce, but I think it has to do with having more than one instance of Stack and disconnecting a cable from V/Oct?

It doesn't seem to happen if I disable the component before changing it, so that's what I do as a workaround.

This is using VCV Rack 1.1.6.

**Comment by mdemanett** [comment]
Think I fixed it -- fix will be in the next release.  Thanks for the report.

**Comment by mdemanett** [comment]
Finally released!
